- README.md
- package.json
- src/components/Actions/ERC20L1Actions.tsx
- src/components/Actions/ERC20L2Actions.tsx
- src/components/Actions/ERC721L1Actions.tsx
- src/components/Actions/ERC721L2Actions.tsx
- src/components/Actions/EthL1Actions.tsx
- src/components/Actions/EthL2Actions.tsx
- src/components/App/index.tsx
- src/components/AssetDropDown/index.tsx
- src/components/Balance/ERC721Balance.tsx
- src/components/Balance/index.tsx
- src/components/Header/index.tsx
- src/components/TabsContainer/index.tsx
- src/components/Transactions/index.tsx
- yarn.lock
Need to update yarn.lock after https://github.com/OffchainLabs/token-bridge-sdk/pull/21 is merged before merging.
> bump token-bridge-sdk version 

- src/util/web3.ts
Currently clicking "Add/Switch to Arbitrum Network" causes the following error to be printed to the console and prevents MetaMask from popping up:
`"Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'. Received: 0x066eeb"`
`ethers.utils.hexValue` strips leading zeros from the chainId string which fixes the bug.
> Fix "Add/Switch to Arbitrum Network" button

- src/state/app/state.ts
fixes https://github.com/OffchainLabs/arb-token-bridge/issues/71
this was a bug inherited from the old UI; with https://github.com/OffchainLabs/token-bridge-sdk/commit/27ca37b37a19be38bc8905f1e2e1574012381c20, we ensure we have access to the current token's decimals (otherwise it may not currently be included in BridgeTokens)
> fix pending withdrawal decimals

- src/state/app/state.ts
fixes https://github.com/OffchainLabs/arb-token-bridge/issues/136
> display OutgoingMessageState "NOT_FOUND" as "unconfirmed"

- packages/token-bridge-sdk/package.json
- packages/token-bridge-sdk/src/test/test.ts
- packages/token-bridge-sdk/src/util/graph.ts
- packages/token-bridge-sdk/tsconfig.testing.json
- yarn.lock
Currently the graph query assumes that a withdrawal has a GatewaySet event for its corresponding token, which is no longer true w/ permissionless token bridging.
We're only using the gatewayset info/join table to the get the L1 token address, so this workaround just parses the address out of the calldata instead.
> get l1 token address from withdrawals from calldata (not from graph table)

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
To repro: trigger a token withdraw while connected  to the L1 side, and after the network switch, w/ a bit of luck, the page will error. 
I'd rather change the default arbTokenBridge state to null for initial load (here https://github.com/OffchainLabs/arb-token-bridge/blob/ecc62b372203322454da95b2b49c64c2489be835/packages/arb-token-bridge-ui/src/state/app/state.ts#L86) and do away w/ arbTokenBridgeLoaded altogether, but I'd want to first confirm that that doesn't break other assumptions.
> fix network switch bug: check  arbTokenBridgeLoaded in TokenButton

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
There are cases in which a action is being taken against the wrong network  (i.e.) https://etherscan.io/tx/0x4c9e6855be18ee310a9e83f4c1b3b81d66782286d1c7f16a578c47cf300df4c1
My best guess (still haven't reproduced) is that that wallet_switchEthereumChain fails silently for some combo of metamask versions and browsers (?), which leads to a signer speaking to a mismatched connected wallet. 
This "can't hurt" check should prevent it while we figure out how to better handle it.
> sanity check current connected wallet before deposit/withdraw action

- packages/arb-token-bridge-ui/src/components/TokenModal/TokenModal.tsx
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
adding via l2 address (for a token that was already registered but then paused) was slipping through the cracks; this is a keep-it-simple-stupid check at the end
> add explicit disabled/paused check

- packages/arb-token-bridge-ui/src/components/TokenModal/TokenModal.tsx
- packages/arb-token-bridge-ui/src/tokenLists.tsx
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
the search-unimported-lists features isn't on this branch; this just sets the groundwork and ensures the UI plays nicely with the new list format https://github.com/OffchainLabs/arb-token-lists/pull/9
> handle arb token lists with L1 tokens

- packages/arb-token-bridge-ui/src/components/TokenModal/TokenImportModal.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
The issue with the approval not popping up was caused by us relying on the `allowed` property of the token on https://github.com/OffchainLabs/arb-token-bridge/pull/257/files#diff-286a4ee4334ef698f2f4080f95722061ff721facd19401fdd32279bf686c1e91L264. 
The `allowed` property is determined in `arb-ts` at https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-ts/src/lib/l1Bridge.ts#L219 by checking if the allowance is greater or equal to half of `0xffffffffffffffffffffffff`, meaning if you set the allowance to be `HALF + 1` and then later want to bridge over `HALF + 100`, the info you'd get was that it was allowed, even though you haven't allowed that amount. 
The fix for the bridge UI was to always check for allowance, and not to rely on the `allowed` property. 
Not sure if any …
> fix: always check for allowance

- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- packages/token-bridge-sdk/src/index.ts
In this PR:
* Switched token approvals to use `@arbitrum/sdk`
* Switched ETH balance updates to use `@arbitrum/sdk`
* Got rid of the `l1NetworkIDCached` callback and added a `l1NetworkID` memoized property
* Added `getL1ERC20Address` and `getL2ERC20Address` which were on the `Bridge` object before
* Kept the same function signatures to minimize changes
> refactor(sdk): update balances, token approvals and addresses

- packages/arb-token-bridge-ui/src/components/TokenModal/TokenImportModal.tsx
- packages/arb-token-bridge-ui/src/components/TokenModal/TokenModal.tsx
- packages/arb-token-bridge-ui/src/components/TokenModal/TokenModalUtils.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/useWithdrawOnly.tsx
- packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- packages/token-bridge-sdk/src/index.ts
In this PR:
- What should we use as the default value for `decimals`? In `arb-ts` [we used 18](https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-ts/src/lib/l1Bridge.ts#L202).
> refactor(sdk): update methods for retrieving L1 and L2 token data 

- packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTable.tsx
- packages/arb-token-bridge-ui/src/components/common/ExplorerLink.tsx
- packages/arb-token-bridge-ui/src/components/syncers/RetryableTxnsIncluder.tsx
- packages/arb-token-bridge-ui/src/state/app/actions.ts
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/token-bridge-sdk/package.json
- packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- packages/token-bridge-sdk/src/hooks/useTransactions.ts
- packages/token-bridge-sdk/src/index.ts
- yarn.lock
Still some open qs r.e. potential new UX
> use arbitrum/sdk: retryables strategy

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/hooks/useNetworks.ts
- packages/arb-token-bridge-ui/src/hooks/useSigners.ts
- packages/arb-token-bridge-ui/src/util/index.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
In this PR:
- `const { status, l1Network, l2Network, isConnectedToArbitrum } = useNetworks()`
- The idea is to switch to this hook to be the source of truth for data on the networks, instead of keeping it in a global state
- `const { status, l1Signer, l2Signer } = useSigners()`
- The idea is same as above, have the hook be the source of truth for signers instead of keeping them in a global state
> refactor(sdk): handle network switching

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useL2Approve.tsx
- packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- packages/token-bridge-sdk/src/hooks/useTransactions.ts
Using the same setup as withdraw-only token to maintain the list. Implemented the l2 approval logic because the l2bridge in arb-ts does not have it. Tested with LPT up to the approval tx initiation.
> Add list of token that require l2 approve

- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
L2 NodeInterface under-estimate gas when there is gas refund. Previously in [arb-ts](https://github.com/OffchainLabs/arbitrum/blob/2122496cb932e0453345c12ec0a20b294c2e2841/packages/arb-ts/src/lib/bridge.ts#L343) a 50% buffer is used by default as a workaround. Adding `retryableGasOverrides` here to restore old behavior before NodeInterface is fixed.
> fix: l2 gas buffer

- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
> fix: wrong provider used in getL2GatewayAddress

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/App/AppContext.tsx
- packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTable.tsx
Previously, `App.tsx` and `TransactionsTable.tsx` were both using the `useBlockNumber` hook, and had their own record of the current L1 block number. As the default value is `0`, this was causing wrong time estimations until a block is produced and the value in `TransactionsTable.tsx` is updated. 
Creating a context and lifting the state up seemed like the best solution, as we'll certainly need a global context going forward.
> fix: lift state for current l1 block number

- packages/arb-token-bridge-ui/src/components/TokenModal/TokenImportModal.tsx
Our `searchForTokenInLists` callback was dependent on a couple of parameters that change often, which caused some unnecessary rerenders and overall janky experience. Wrapping those values in refs via `useLatest` fixes this.
Before the fix: 
https://user-images.githubusercontent.com/20543771/165960623-98d92886-a649-48da-ae85-fba48c79dc5a.mp4
After the fix:
https://user-images.githubusercontent.com/20543771/165960633-8ec82c37-d6bb-4dd1-adfc-fb4d46d9cb89.mp4
> fix: prevent unnecessary rerenders of search callback

- packages/arb-token-bridge-ui/src/components/TransferPanel/useWithdrawOnly.tsx
FRAX is not using the standard bridge token, their L2 token [0x17FC002b466eEc40DaE837Fc4bE5c67993ddBd6F](https://arbiscan.io/address/0x17FC002b466eEc40DaE837Fc4bE5c67993ddBd6F)
> fix: add FRAX to withdraw only list

- packages/arb-token-bridge-ui/src/components/syncers/PendingTransactionsUpdater.tsx
If seqNum is missing (e.g. user exited the page before l1 tx confirmed) we need to retrieve it in `checkAndUpdatePendingTransactions` so that the user can re-execute / redeem a failed retryable in https://github.com/OffchainLabs/arb-token-bridge/blob/f0001ab6234966c3b10ed3419a47bcd09e2ec31a/packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTable.tsx#L124-L125
Alternatively we can retrieve it within the `redeemRetryable`, not sure which is better because this patch is ugly too.
> fix: missing seqNum in pending deposit-l1 txs

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
One problem with the current implementation of the `useNetworksAndSigners` hook is that state isn't reused between hooks, so if we have multiple components that use the hook, the logic inside gets executed multiple times unnecessarily, which also does bunch of unneeded network requests.
This PR lifts the state up in a context without changing the API of the hook, and also sets up stuff for a future refactor where we can get rid of all the unnecessary optionals in the return type.
> refactor: lift networks and signers state to context

- packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTable.tsx
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/token-bridge-sdk/src/hooks/arbTokenBridge.types.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
If a user ever withdrew a token that is broken on L1 (e.g. balance, allowance, or transfer revert), the pending withdrawal list will fail to render at all. One example is the now disabled [DEFI5 token](https://etherscan.io/address/0xfa6de2697D59E88Ed7Fc4dFE5A33daC43565ea41#readProxyContract) which broke the UI for address 0x68a9857b0e540e5a800151d3e4a33037191a5dc4. This PR suppress error in the `setInitialPendingWithdrawals` code path.
> fix: handle pending withdrawals for invalid tokens

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
Simplifies the flow and removes the need to check for the users' L2 balance. We now only check the L1 address to know if we should disable deposits.
> feat: make the withdraw only token list work for multiple L2s

- packages/arb-token-bridge-ui/src/components/MainContent/MainContent.tsx
The check if the transaction already exists in the map was in the wrong place, so sometimes the withdrawal initiation transaction was overriding the transformed L2-to-L1 message.
> fix: properly dedupe withdrawals

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/MainContent/MainContent.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
In this PR:
* Show withdrawal confirmation dialog before attempting a network switch (https://github.com/OffchainLabs/arb-token-bridge/commit/a12965afd8a83abbfa914d3fd765b022489ca425)
* Wrap `TransferPanel` and `ExploreArbitrum` into separate `AnimatePresence` components as the `exitBeforeEnter` prop was causing only one of those to render, effectively cancelling the transfer (https://github.com/OffchainLabs/arb-token-bridge/commit/f555c1736856adb7a656bdae1cbc9345b20aee6f)
* Don't wait for pending withdrawals to load before rendering cards (withdrawals will now be loaded from local cache and show `Calculating...` until fetched from subgraph/logs and the wait time is calculated) (https://github.com/OffchainLabs/arb-token-bridge/commit/68756eac8a8d2fd2d502d3b259af0f97b2d69c7a)
> fix: handle mid-transfer network switch 

- packages/arb-token-bridge-ui/public/arbed_42170_gemini_token_list.json
- packages/arb-token-bridge-ui/public/arbed_42170_uniswap_labs_default.json
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenImportDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/common/SafeImage.tsx
- packages/arb-token-bridge-ui/src/tokenLists.tsx
In this PR:
* Add token lists for Arbitrum Nova (https://github.com/OffchainLabs/arb-token-bridge/commit/4d55890bd94ed2b73910c78784cde4530060dda0)
* Only show fast bridges for withdrawals from Arbitrum One (https://github.com/OffchainLabs/arb-token-bridge/commit/9f97b46429f308e7c23ca674e20e5eb97e27640a)
> feat: add token lists and hide fast bridges for arbitrum nova

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainUtils.ts
Disables UI elements like the main input, buttons to move funds and the gas summary in the few seconds while the switch between different L2s is happening.
> fix: disable interaction while switching L2 chain

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
If the user was connected to Arbitrum Nova in their wallet, and they set up everything for a deposit (rightfully expecting the deposit to land to Arbitrum Nova), the bridge would prompt a switch to Mainnet in order to confirm the deposit. 
Problem: no `l2ChainId` search param would be present, and the preferred L2 would default to the first one, i.e. Arbitrum One.
> fix: set the connected L2 chain as the preferred one

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
- yarn.lock
This PR only supports UD on Ethereum mainnet and not the ones on Polygon.
Development was done using Polygon UD
Polygon Mainnet address provided by Unstoppable:
> Here's a test address for mainnet `0x499dD6D875787869670900a2130223D85d4F6Aa7` with reverse resolution configured
To know if an address has reverse resolution set up, check that `reverseOf` returns the token id
Polygon: https://polygonscan.com/address/0x3E67b8c702a1292d1CEb025494C84367fcb12b45#readContract
Mainnet: https://etherscan.io/address/0x049aba7510f45BA5b64ea9E658E342F904DB358D#readProxyContract
> feat: add unstoppable domains support

- packages/arb-token-bridge-ui/src/index.tsx
- packages/token-bridge-sdk/src/hooks/useBalance.ts
- packages/token-bridge-sdk/src/hooks/useChainId.ts
- packages/token-bridge-sdk/src/hooks/useGasPrice.ts
In this PR:
* Created a new hook `useChainId` which is useful when using the chain id from provider as a query key in `useSWR`
* Modified `useBalance` a bit so it doesn't catch errors thrown in the fetcher; retries now work properly
* Ignored errors related to `eth_getBalance` in Sentry
> refactor: enable eth balance fetch retries in useBalance

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
This created an issue where Kyber token could be added twice and display an unknown token logo. Here we lowercase when adding new tokens for consistency and to avoid issues like that.
@spsjvc as per your request for the search bar to be case insensitive as well - that's already the case, no changes needed
> fix: lowercase token address when adding to token list

- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
Changed withdrawal calculation to be based on hours instead of days. That's also the case if withdrawal time is longer than a day.
> feat: change withdrawal calendar to be hour based

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/DepositConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderNetworkInformation.tsx
- packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
- packages/arb-token-bridge-ui/src/components/common/WithdrawalCountdown.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
> refactor: only accept chain id as arg in `isNetwork`

- packages/arb-token-bridge-ui/src/components/App/AppContext.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/common/SafeImage.tsx
React would throw errors (updating state of an unmounted component).
TransferPanel: in try catch block, `finally` would get executed after the panel unmounts following transfer initialization. Solution: move setTransferring to layout context.
> fix: react unmount errors

- packages/arb-token-bridge-ui/src/hooks/__tests__/useArbQueryParams.test.ts
- packages/arb-token-bridge-ui/src/hooks/useArbQueryParams.tsx
allow -0 to return as -0 for now as it doesn't affect usage
> fix: allow leading zeros in input

- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderMenu.tsx
> feat: add dropdown icons to navbar

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/hooks/useTwitter.ts
These are only a few deps that were added that didn't impact performance: tested the transfer panel and amount input field.
There are more such as `actions.app` which I'm unsure about since it could cause unnecessary loops. Also `dispatch` doesn't have to be added to deps and the warning will be gone should we update to React 18 at some point.
I may add a couple more once we see those not to cause any issues.
Would be nice for a reviewer to test this manually as well to make sure it runs smoothly on other machines still.
> fix: react warnings

- packages/arb-token-bridge-ui/package.json
There's no need to run these commands as the TailwindCSS plugin is included in the Webpack config and this line is enough:
https://github.com/OffchainLabs/arb-token-bridge/blob/5c0c634d301f8639a5c258f441c9aceae82736b7/packages/arb-token-bridge-ui/src/index.tsx#L16
> chore: remove redundant tailwind build

- packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositETH.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
Non-english language (e.g. French) allows `,` as decimal separator (instead of comma).
Using `cy.type(0.0001)` type `0,0001` in the input. We're now reading the formatted version in e2e test.
> test: fix numbers wrongly formatted in non-english browser

- packages/token-bridge-sdk/src/common.ts
- packages/token-bridge-sdk/src/withdrawals/__test__/fetchETHWithdrawalsFromEventLogs.test.ts
- packages/token-bridge-sdk/src/withdrawals/__test__/fetchETHWithdrawalsFromSubgraph.test.ts
- packages/token-bridge-sdk/src/withdrawals/__test__/fetchETHWithdrawalsTestHelpers.ts
- packages/token-bridge-sdk/src/withdrawals/__test__/fetchTokenWithdrawalsFromEventLogs.test.ts
- packages/token-bridge-sdk/src/withdrawals/__test__/fetchTokenWithdrawalsFromSubgraph.test.ts
- packages/token-bridge-sdk/src/withdrawals/__test__/fetchTokenWithdrawalsTestHelpers.ts
Updated the test-addresses + RPC endpoint + txHashes used in the `arbOne` subgraph.
> test: update tests for withdrawals to point to arbitrum one

- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
When using `getDepositRequest`, we're always relying on the passed in `l1Provider`.
> fix: use deposit request for token deposits

- packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
- packages/token-bridge-sdk/src/withdrawals/fetchTokenWithdrawalsFromSubgraph.ts
This PR:
* Filters out withdrawal transaction receipts that resolve to `null` until we support them
* Adds a notice on the transaction history that says we currently don't display withdrawals older than a year
> fix: handle old withdrawals

- audit-ci.jsonc
- packages/arb-token-bridge-ui/package.json
- yarn.lock
remove this because #517 updated the dependency to a non-vulnerable version
> chore: remove inapplicable advisory from ignore list

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
We are going to have extra data below network selectors, such as advanced settings with destination address input.
This causes layout issues in the summary panel: `Bridging summary will appear here text` is shifted down.
**Solution:** only added `<div className="flex flex-col">` wrapper. GitHub formatting might make it harder to see.
Before:
After:
Non-empty summary panel unaffected:
> fix: adjust spacing in summary panel

- packages/arb-token-bridge-ui/src/components/App/App.tsx
Pin commit of `warningToken`, if `warningToken` changes in master in token-list repo, we will still be fetching the same version which we knows is working.
> fix: pin commit of warningTokens.json

- packages/arb-token-bridge-ui/src/hooks/useTwitter.ts
Text is as seen on https://github.com/OffchainLabs/arbitrum-docs/pull/64
connect to testnet and click "Request ETH from the Nitro Testnet Twitter faucet!"
it should say
> Ok I need @ arbitrum to give me Arbitrum Goerli testnet gas. I can't wait to start developing on @nitro_devnet.  SEND HERE: {wallet address}
^ space is added to not trigger github tag
> chore: update twitter request faucet text

- packages/arb-token-bridge-ui/src/components/common/Header.tsx
Adds a link to the Arbitrum Nova portal in the Ecosystem dropdown.
> feat: add link to the arbitrum nova portal

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/common/Button.tsx
The enabled styles currently make the button look disabled
Before
After
closes #593
> style: update enabled Add button styles

- packages/token-bridge-sdk/src/util/deposits.ts
Only creation time was visible for completed token deposits
Both creation + completion time is visible for completed token deposits
> fix: show completion time for token deposits in tx history

- packages/arb-token-bridge-ui/src/components/MainContent/MainContent.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/PendingClaimsInfo.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/WithdrawalsReadyToClaimInfo.tsx
- packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
Earlier there used to be Pending transaction cards right in front of the user and not hidden in the Tx history panel. With this feature, we will have this pending tx info right at the page center as well.
- Have some pending, claimable transactions
- The banner with the text `You have [X] withdrawals ready to claim.` will appear right on top of the transfer panel in front page. See the screenshot.
> feat: show pending claim withdrawals' banner on front page

- packages/arb-token-bridge-ui/src/components/common/SidePanel.tsx
- packages/arb-token-bridge-ui/src/pages/_app.tsx
- packages/arb-token-bridge-ui/src/state/app/utils.ts
A minor enhancement to add timezone offset abbreviations to the dates being shown in transaction history.
I added it as a separate PR to confirm the approach and experience.
Note: Not ALL timezones map to an abbreviation/short name like `GMT`, `PST`, etc. In those cases, the library fallbacks to showing `GMT +5.30` format for timezones.
Screenshots : 
<p float="left">
</p>
> feat: display timezone in transactions

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistory.tsx
> fix: tab text wrapping to next line

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistory.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderNetworkInformation.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderNetworkNotSupported.tsx
- packages/arb-token-bridge-ui/src/components/common/MainNetworkNotSupported.tsx
- packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
- packages/arb-token-bridge-ui/tailwind.config.js
- Fixed distorted icons in header introduced after removing custom CSS classes
- Added the width classes as a part of tailwind config and did a prettier-format after that.
> fix: distorted icons in header

- packages/arb-token-bridge-ui/src/hooks/useClaimWithdrawal.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- Added Sentry error tracing for the intermittent `Can't claim withdrawal yet` issue
- Added `throw error` to the try-catch block in SDK to propagate the error further
> fix: added error tracing for withdrawal claiming flow

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenImportDialog.tsx
Add some copy to explain that the bridge doesn't support rebase tokens
For most tokens, this can be ignored and is not a warning, so it's in blue.
Try to import a token on the token search panel. Trigger the import token dialog to open.
> feat: add info section about lack of support for rebase token to import token dialog

- packages/arb-token-bridge-ui/src/components/App/AppContext.tsx
- As a part of [this](https://github.com/OffchainLabs/arb-token-bridge/pull/635) refactor, we abstracted dispatch functionality into a single, reusable hook.
- In one of the instances (where we set the current L1 block number app-wide) we used this hook OUTSIDE the app's context provider wrapper, which rendered it useless, hence falling back to 0 in this case.
- To display the time remaining to withdraw, we use this L1 block number set in app-state, which was being incorrectly used as 0 and messed up all the calculations.
> fix: incorrect time remaining to withdraw being displayed

- packages/arb-token-bridge-ui/synpress.config.ts
- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/approveToken.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/importToken.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/login.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/readClassicDeposits.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/txHistory.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
- packages/arb-token-bridge-ui/tests/support/common.ts
- packages/arb-token-bridge-ui/tests/support/index.ts
Until now a lot of tests were dependent on the Metamask state, such as network creation, previously connected network, wallet being connected to dapp. This also made some tests dependent on each other in some cases.
This PR introduces the following improvements/fixes:
- Metamask networks are now set up before all tests run. This means we don't have to e.g. run `withdrawETH` (which previously also did L2 setup) to test anything relying on L2 network
- Even though we are still waiting for https://github.com/Synthetixio/synpress/issues/702 fix from Synpress, `cy.login` will now handle itself and skip network connection if already connected to the desired network
- We don't rely on `login.cy.ts` to connect wallet to the bridge anymore. Any first use of `cy.login` will also connect to the …
> test: e2e independent of Metamask state

- packages/arb-token-bridge-ui/src/state/app/state.ts
E2E test for withdrawing the ERC20 token was failing in CI (and later, locally)
- As a part of https://github.com/OffchainLabs/arbitrum-token-bridge/pull/741 we added a UI check for this 
> We were not filtering withdrawal transactions by current account before loading in the UI - so all the transactions in the state would get considered for UI
- While running E2E, the withdrawals are initiated by the locally configured network, and due to this change, we filtered to only show those transactions whose `caller matches the current wallet address` - Which is not the case in E2E.
Reverted this check as our previous issue was getting fixed by the state check revalidation only - so this check was redundant. The issue being fixed by https://github.com/OffchainLabs/arbitrum-token-bridge/pull/741 …
> fix: reverted the additional UI check which failed E2E

- packages/arb-token-bridge-ui/package.json
- yarn.lock
This pull request removes the **@tailwindcss/forms** dependency from the project. The motivation behind this change is to simplify the codebase and reduce the overall size of the project. By removing this dependency, we can also potentially improve the performance of the application.
Since the **@tailwindcss/forms** was not used in the application, you can still run it without any error.
> chore: uninstall @tailwindcss/forms

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
Closes #786 
- Removed USDT from `withdrawOnly` config which was disabling it's deposit.
> fix: allow USDT deposits to Arbitrum Nova

- packages/arb-token-bridge-ui/tests/support/common.ts
There's a pattern where flaky tests (especially failing to type or initially load the page) would always fail their re-attempts.  The underlying issue is not clear but it could be that cypress is not starting the test over in a fresh state, but reusing the previous instance for next attempts.
Not sure if that fixes our issue but if the mentioned problem is the cause, reloading the page after every failed attempt could make our tests much less flaky.
> test: Reload on failed attempts

- packages/arb-token-bridge-ui/src/components/common/HeaderMenu.tsx
Fixed logic for highlighting link color in the mobile header menu.
<p float="left">
</p>
> fix: menu text color not visible in mobile

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
As a part of #742 we updated the Input panel component's positioning (to have an absolutely positioned background). That resulted in messing up the size of the token-search panel, which is set `absolute` inside the Input panel.
We fixed its impact on large screens, but it did not get resolved entirely on mobile. This PR fixes the mobile view of token search.
<p float="left">
</p>
> fix: token search popup height in mobile

- packages/arb-token-bridge-ui/jest.config.js
Fixes test running with Jest when there's node modules that need to be transformed first. We now keep a list of those.
Source: https://github.com/vercel/next.js/issues/36077#issuecomment-1096635363
> test: keep list of node modules that need transformation

- packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
It's been a while since we released the Preferences panel. We can remove the new badge.
> chore: remove the New indicator from preferences

- packages/arb-token-bridge-ui/tests/e2e/specs/txHistory.cy.ts
In our transaction history test, we search for "invalidTransactionHash" to test for the `no results found` case.
It'd be better to use a much shorter invalid string here. Using "0xx" shaves 6s off our e2e test suite, given that each key-stroke takes 150ms, and longer typed strings increase the chances of flakiness. 😄 
---
> test: improve invalid tx search string in e2e

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTable.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/hooks/useAccountType.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/switchNetworks.cy.ts
Currently our `useIsConnectedWithSmartContractWallet` hook can return either a `boolean` or `undefined`. There are some UI changes required for the custom address that are conditionally rendered based on `useIsConnectedWithSmartContractWallet` being `true`.
Therefore, we have to make checks like `useIsConnectedWithSmartContractWallet !== false` to cover the `undefined` case. This can be a bit confusing. This change will make it more clear:
`const { isEOA, isSmartContractWallet } = useAccountType()`
> refactor: move account type check to `useAccountType`

- packages/arb-token-bridge-ui/tsconfig.json
With baseUrl, import paths are automatically added by VSCode as `src/....`
This PR will allow VSCode to add `../../` relative path as import path
> chore: remove `baseUrl` from `tsconfig.json`

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/hooks/arbTokenBridge.types.ts
- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/util/L2NativeUtils.ts
Closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/659. Closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/829.
This PR is a simpler version of https://github.com/OffchainLabs/arbitrum-token-bridge/pull/806. It removes the logic around L2-native tokens, and instead keeps a list of them.
Currently, we can only add bridgeable tokens in the token search panel, i.e. tokens which are bridged using the token bridge.
Adding L2-native tokens currently results in a `Token not found on this network.` error which is confusing. In addition, a rare case where a token is present on the same address on both the L1 and the L2 chain (L2-native) resulted in the L2-native token not being displayed, which is also confusing.
To test out the fix for …
> feat: improve UX for L2-native tokens

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/util/CommonAddressUtils.ts
Updates the token symbol for `USDC` to `USDC.e` whenever it's related to the token representation on Arbitrum One.
When moving from or to Arbitrum One, the token symbol should be `USDC` for Mainnet, and `USDC.e` for Arbitrum One, both in the token selection button, and balance info.
> feat: change symbol from USDC to USDC.e for Arbitrum One

- packages/arb-token-bridge-ui/src/pages/_app.tsx
We don't really maintain version numbers (which is fine, because it's an app and not a public package), and the current setup makes it look like we're always on the same version of the app on Sentry.
N/A
> chore: don't send release data to Sentry

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTableDepositRow.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTableWithdrawalRow.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/DepositCardPending.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardConfirmed.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardExecuted.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardUnconfirmed.tsx
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
Extension of the PR https://github.com/OffchainLabs/arbitrum-token-bridge/pull/937
Covers all cases wherever we show USDC (symbol and name)
- Log in via any account that has USDC transactions
- Search for USDC in token-search
- Check for the USDC symbol, name in Transfer panel and Tx history, they will now be chain specific.
> fix: patch token name and symbol for USDC and USDCe

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderNetworkInformation.tsx
- packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
Closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/916
- Some elements might flicker for the smart contract wallet users. It's because we get the account type async and some UI will update accordingly. However, we make sure that EOA user experience hasn't changed (no side-effects for them)
> fix: disable network switching for contract wallets

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
Step 1. Click the network swapper so that you are in withdrawal mode (Metamask connected to Mainnet):
Step 2. Change wallet in metamask. You will notice that you are in deposit mode (the transfer button says 'Move funds to Arbitrum One' but the UI says our origin network is Arbitrum One. The balances are flipped too, so it's just UI issue.
We need to update `to` and `from` states when `walletAddress` changes.
> fix: update networks when switching wallets

- .github/workflows/build-test.yml
Adds a new job `Test E2E Success` that runs only if all E2E tests were successful. Then we can have `Test E2E Success` be required to merge PR instead of having to list out all the E2E tests.
> ci: run job after e2e is successful

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
Issue: Network not updating in the transfer panel
Reason: `walletAddress` dependency would go to `undefined` when switching networks and trigger `useEffect`, which would override the expected network with `externalFrom` and `externalTo`
> fix: update ETH balances when wallet changes

- packages/arb-token-bridge-ui/src/pages/api/screenings.ts
Adds some super basic bot prevention by checking the user agent header for common HTTP libraries. In reality, the request should always come by a user from a web browser.
You can test it with Python by running `python` and then in the REPL:
```
>>> import requests
>>> requests.get("https://arbitrum-token-bridge-git-feat-bot-prevention-offchain-labs.vercel.app/api/screenings").text
'{"blocked":false}'
```
Even when you don't provide an address, your request with `python-requests` will instantly return a response.
> feat: add basic bot prevention for screenings endpoint

- .github/actions/build-artifacts/cache/action.yml
- .github/actions/build-artifacts/restore/action.yml
If a job depending on `cache artifact` action is failing, when rerun, it will try to restore `build-artifacts-...-2`, which doesn't exist (the artifact was cached with `build-artifacts-...-1`.
I removed the `run_attempt` at the end, so we can safely rerun failed tests depending on `cache artifact`
> ci: remove `run_attempt` from artifact cache keys

- yarn.lock
rerunning tests for #1044 
Bumps [word-wrap](https://github.com/jonschlinkert/word-wrap) from 1.2.3 to 1.2.4.
- [Release notes](https://github.com/jonschlinkert/word-wrap/releases)
- [Commits](https://github.com/jonschlinkert/word-wrap/compare/1.2.3...1.2.4)
> chore: bump word-wrap from 1.2.3 to 1.2.4

- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
We needed to sanitize the USDC token name and symbol for Goerli as well, it was left out since Goerli support for USDC/e came a bit after our sanitize functions.
<p float="left">
</p>
<p float="left">
</p>
> fix: show USDCe for Arbitrum Goerli as well

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
Some external change to WC caused it to only provide an L1 signer if connected to Ethereum, and an L2 signer if connected to Arbitrum.
In our `transfer()` method we've been checking for both L1 and L2 signers, regardless of the account type. Currently SCW are throwing when trying to transfer.
We need to keep the current implementation for EOA, and only check for L1 (for deposits) and L2 (for withdrawals) when using SCW.
> fix: require only connected network's signer with scw

- .github/workflows/build-test.yml
- .github/workflows/pr-title-check.yml
https://github.com/OffchainLabs/arbitrum-token-bridge/queue/master
CI workflows are currently not running when PR joined merge queue
this should fix it
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
> ci: run on merge queue

- packages/arb-token-bridge-ui/src/components/App/WelcomeDialog.tsx
- packages/arb-token-bridge-ui/src/components/common/Dialog.tsx
closes #1070 and added some additional CSS cleanup
> chore: cleanup welcome dialog

- packages/arb-token-bridge-ui/package.json
- yarn.lock
Includes https://github.com/OffchainLabs/arbitrum-sdk/pull/327
> chore: bump sdk to 3.1.9

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
- packages/arb-token-bridge-ui/src/components/common/SettingsDialog.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
> feat: orbit support for network selection dropdown

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTableDepositRow.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/DepositCardPending.tsx
- packages/arb-token-bridge-ui/src/components/common/DepositCountdown.tsx
- packages/arb-token-bridge-ui/src/hooks/arbTokenBridge.types.ts
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/arb-token-bridge-ui/src/state/app/utils.ts
- packages/arb-token-bridge-ui/src/util/deposits/fetchDeposits.ts
- packages/arb-token-bridge-ui/src/util/withdrawals/fetchWithdrawals.ts
Testnets aren't supposed to take 15-ish minutes to deposit. This PR fixes that and shows <1 minute remaining for deposits in case the transaction is not a mainnet transaction.
> fix: correct the deposit countdown timer for testnets

- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCDeposit/USDCDepositConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCWithdrawal/USDCWithdrawalConfirmationDialog.tsx
USDC modals confirm button should be disabled when the modal is opened, and state should be updated to enabled when all checkboxes for the current tab are checked.
Currently, if all checkboxes are checked, and modal is closed, on reopening the modal, the button is enabled.
- Open USDC modals (select USDC.e, or native USDC and start a transfer)
- Check all checkboxes and close the modal (either with cancel or confirm)
- On reopening the modal, confirm button should be disabled. Checkboxes should be unchecked
> fix: Reset USDC checkboxes modals

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistory.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTableCctp.tsx
- packages/arb-token-bridge-ui/src/components/syncers/PendingTransactionsUpdater.tsx
- packages/arb-token-bridge-ui/src/state/cctpState.ts
Hide CCTP tabs (and prevent fetching) non non-valid networks. CCTP should only be display on
Goerli/ArbitrumGoerli and Mainnet/ArbitrumOne. It should be hidden on other networks, and no call to API (cctp/deposits, cctp/withdrawals) should be made.
> fix: hide cctp on non valid networks

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTableRowAction.tsx
Only affecting the tx rows, pending cards are claimable.
Implemented the same behavior as in [the pending claimable card](https://github.com/OffchainLabs/arbitrum-token-bridge/blob/master/packages/arb-token-bridge-ui/src/components/TransferPanel/ClaimableCardConfirmed.tsx#L56)
Before:
After:
> fix: resolve issue with disabled claim button for Orbit

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTable/TransactionsTableClaimableRow.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/ClaimableCardUnconfirmed.tsx
- packages/arb-token-bridge-ui/src/components/common/WithdrawalCountdown.tsx
Some chains, especially testnet L2s, have very volatile block time and there's a significant inaccuracy in estimating the remaining time. Also, it's less accurate when caching these details.
Now we base the withdrawal time on tx creation date. With this we can also skip RPC calls for `firstExecutableBlock` and simply use `createdAt` from tx object (next PR)
> refactor: base tx remaining time on tx creation date

- packages/arb-token-bridge-ui/src/pages/_app.tsx
- Sets maxValueLength to `0`, which is passed into [`truncate`](https://github.com/getsentry/sentry-javascript/blob/a57b66d48d6ba95f35f07145e6e6ae7f864280a3/packages/utils/src/string.ts#L12) so it is not truncated.
- closes #1173
> chore: removes max length from sentry values

- .github/ISSUE_TEMPLATE/config.yml
- packages/arb-token-bridge-ui/src/constants.ts
All old foundation links redirect to support.arbitrum.io now
> chore: update foundation links

- packages/arb-token-bridge-ui/src/pages/index.tsx
- packages/arb-token-bridge-ui/src/util/AddressUtils.ts
- packages/arb-token-bridge-ui/src/util/RetryableUtils.ts
- Adds an unused parameter declaration of `_` in catch blocks in order to prevent errors in some browsers (see [caniuse for this feature](https://caniuse.com/?search=optional%20catch%20binding))
- We could also modify our `tsconfig.json` in order to build a higher compatibility bundle, but that's a much larger change. 
- closes #1181
> fix: fixes optional catch binding error

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/pages/index.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
- yarn.lock
https://github.com/OffchainLabs/arbitrum-sdk/pull/343 is the main upgrade that greatly reduces the number of outgoing rpc calls when fetching withdrawals from event logs.
It also scales and saves more requests the more pages we fetch. Some comparisons (with 5 claimable withdrawals), the number of RPC calls you see is the total number per session (including previous pages):
1st page:
vs
2nd page:
vs
3rd page:
vs
Also, adding Stylus as a custom network was removed because it's now included in the new SDK version.
> chore: bump sdk version to orbit

- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
Steps to reproduce:
- Load tx history on Arbitrum Goerli (L2). Withdrawal claim button should be disabled.
- Now switch the network to Goerli (L1). Withdrawal claim button is now enabled.
- Click on the newly enabled claim button - you will get the outbox message error as present in screenshot.
To successfully complete the claim process, we require the outbox message to be present in the state. (pendingWithdrawalsMap)
Tx history doesn't reload when we switch from child-to-parent chain, but we still reset the withdrawals (claims) and hence clear the outbox events loaded in the state when wagmi detects the connection change (even from child to parent network). When the claim button is pressed, we cannot find the outbox event and throw the error.
Fix: Instead of listening to wagmi connection …
> fix: outbox message not found error on claim

- .github/workflows/build-test.yml
Pinning the ref for `nitro-testnode` to an older one until we add the necessary additional config to make it work.
> ci: use older version of nitro-testnode

- packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
Currently, the child chain resets to the default when switching back from the parent chain.
Eg. when connected to `Nova <> Mainnet`, when the user connects the wallet to `Mainnet`, the pair reverts to `One <> Mainnet` in the Bridge.
This fix sets the child(l2/l3) chain id in query params to remember that when switching back from parent.
Eg. when connected to `Nova <> Mainnet`, when the user connects the wallet to `Mainnet`, the pair is preserved to `Nova <> Mainnet`.
Tested with all pairs
- Mainnet <> One / Nova
- Sepolia <> Arbitrum Sepolia <> Xai / Stylus
> fix: set `l2ChainId` after connection

- yarn.lock
Duplicate of https://github.com/OffchainLabs/arbitrum-token-bridge/pull/1241
> chore: bump crypto-js from 4.1.1 to 4.2.0

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/defaults.ts
- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/util/TokenApprovalUtils.ts
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
* Renamed `getTokenAllowanceForSpender` to `fetchErc20Allowance`
* Made the parameters more aligned with the actual contract method parameters
* Removed `getL1TokenAllowance`
* It was used only once, and it confused me, as I thought it could fetch allowance for any spender, but the spender was hard-coded to the L1 gateway
* Now we just use `fetchErc20Allowance` and we fetch the L1 gateway address right before that
* Renamed `getL1GatewayAddress` to `fetchErc20L1GatewayAddress`
* Renamed `getL2GatewayAddress` to `fetchErc20L2GatewayAddress`
* Changed prefix to `fetch` as imo it's more intuitive that it's doing some async fetch
* Created `fetchErc20Data` to fetch `name`, `symbol` and `decimals` for a token
* Currently unused, but will be used in the custom fee token pull request
Everything …
> refactor: rename and rearrange token utils

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
This refactor is necessary to enable some custom fee token functionality which was just too complicated to do with the current code setup.
Got rid of the following variables inside `TransferPanel`:
* `amountNum`
* just a parsed numerical version of `amount` that was used in a few spots, I think it's easier to not worry about one extra variable that's not that valuable
* `ethBalance`
* it was ETH balance that changed based on whether you are in deposit or withdrawal mode
* `l1Balance`
* this was ETH balance on L1 OR selected token balance on L1, depending if you had one selected
* `l2Balance`
* same as above but for L2
Created a few new variables that hold `number | null` values for both ETH and selected token on both chains: `ethL1BalanceFloat`, `ethL2BalanceFloat`, …
> refactor: update disabled conditions and error messages

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/util/TokenDepositUtils.ts
Currently, we have hard-coded values for token deposit gas estimates, which can be a problem for Orbit chains as the gas limit changes due to the changes in L1 base fee. The reason we had this hard-coding in the first place is not being able to show gas estimates for tokens that the user still hasn't approved to be spent by the gateway. This PR adds a check for that allowance, and falls back to the hard-coded values. Otherwise, we use the actual gas estimates.
The actual transactions were still using the gas estimates from the Arbitrum SDK, so this will just reduce the discrepancy between what was displayed in the gas summary and what the actual transaction had.
It also lays the groundwork for:
- Showing gas summary even when no wallet is connected
- Checking allowance for custom fee …
> feat: fall back to hard-coded values for gas estimates

- packages/arb-token-bridge-ui/src/components/TransferPanel/ClaimableCardUnconfirmed.tsx
Wrong transaction IDs are shown when withdrawing from Orbit chains because deposit card details were shown instead.
Closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/1121
> fix: display correct card details for Orbit withdrawals

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenImportDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts
- packages/arb-token-bridge-ui/src/components/common/AddCustomChain.tsx
- packages/arb-token-bridge-ui/src/hooks/arbTokenBridge.types.ts
- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
- packages/arb-token-bridge-ui/src/util/deposits/helpers.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
- packages/arb-token-bridge-ui/src/util/withdrawals/helpers.ts
In this PR:
* Removed `getL2TokenData` as it was unused
* Removed `getL1TokenData` in favor of `isValidErc20` and `fetchErc20Data`
* It was doing two things: 1) validating that the provided address houses a valid erc-20 contract; 2) fetching the data for that erc-20, so it was a bit hard to understand that looking from a high level
* Now we use `isValidErc20` in places where we were relying on `getL1TokenData` to throw in case of invalid erc-20 (adding token through search field and importing through query param)
* Refactored the code around storing to cache a bit, using local storage instead of session storage now
* Moved some types and utils into `TokenUtils` 
Everything should work the same.
> refactor: clean up utils for fetching erc-20 data

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainErrorMessage.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/errorMessages.ts
Closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/1259.
Right now, we show the exact same error message regardless of whether your balance was less than the amount you were trying to bridge or if you didn't have enough funds to pay for gas. Now that message varies, e.g: 
* `Insufficient ARB. Please add more funds to Goerli.`
* `Insufficient ETH to pay for gas fees. Please add more funds to Arbitrum Goerli.`
Plus it will work for custom fee token, as it will display a different asset than ETH. I'm not too worried about Orbit chains with long names, as it nicely wraps to the next line.
> feat: improve insufficient funds error messages

- packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
Currently if the user is trying to connect to an Orbit network without properly setting up the node, we don't show any warning. This PR does that to improve dev-experience.
> fix: show error message on Orbit connection failure

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
RDNT supports transfers through it's native bridge. https://docs.radiant.capital/radiant/project-info/rdnt-tokenomics
Bridging through Arbitrum Bridge needs to be disabled.
> chore: add RDNT to withdraw only list

- packages/arb-token-bridge-ui/src/hooks/useDeposits.ts
- packages/arb-token-bridge-ui/src/hooks/useWithdrawals.ts
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/arb-token-bridge-ui/src/state/app/utils.ts
https://github.com/OffchainLabs/arbitrum-token-bridge/pull/1233#discussion_r1403328663
> refactor: transform single tx instead of array

- packages/arb-token-bridge-ui/package.json
- yarn.lock
https://nextjs.org/docs/messages/sharp-missing-in-production
fixes this warning on ci
closes #1246
> perf: add sharp for production image optimisation

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenRow.tsx
Production:
This PR:
Closes #1265
> feat: replace L2 with network name

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/common/ExternalLink.tsx
- packages/arb-token-bridge-ui/src/util/CommonUtils.ts
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
Doesn't show for custom fee token chain native currency / ETH / USDC
closes #1304
> feat: show token explorer link for both networks

- packages/arb-token-bridge-ui/src/components/TransferPanel/DepositConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
- packages/arb-token-bridge-ui/src/util/fastBridges.ts
ArbiFRAX support has been discontinued by the external team.
So we are disabling FRAX deposits on our UI.
This PR removes the code related to the instructions for depositing through our UI, making the user never be able to confirm to continue on that route.
Currenly on production:
On this PR:
Eventually we would want to standardise the messaging and dialogs for all withdraw-only tokens (show fast bridge / generic message on dialog to check with token team)
> feat: do not allow FRAX deposit on our ui

- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
Refer to comment on L371:
```typescript
// Everything is in the same currency
// This case also handles custom fee token withdrawals, as `ethBalanceFloat` will reflect the custom fee token balance on the Orbit chain
```
closes #1319
> fix: use native currency, not always ETH on error msg

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
The error is only reproducible on Arbitrum One, not testnets, due to actual gas fees being relatively high to expose the issue
closes #1328
> fix: update withdrawal max amount estimation

- .github/workflows/build-test.yml
- packages/arb-token-bridge-ui/tests/e2e/specs/readClassicDeposits.cy.ts
#1223 has attempted to fix this but as the hotfix ci job is added to the dependency of "needs" jobs,
the `test-e2e-success` job is still skipped whenever any of the e2e tests failed
> ci: always run test-e2e-success job

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistoryTable.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableClaimableRow.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableDepositRow.tsx
> fix: align tx history table headers

- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
Custom gas token deposits wouldn't update because `tx.asset` is a different token. We need to check for `tx.assetType` which is always `ETH`.
> fix: deposit update for custom gas tokens

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/hooks/useTokenLists.ts
On production, ARB is always shown on the Token Search Panel
On this PR, we only want to show it when none of the source and destination chains are an L3 Orbit chain
> feat: hide ARB on token search panel for Orbit chains

- packages/arb-token-bridge-ui/src/pages/api/cctp/[type].ts
- packages/arb-token-bridge-ui/src/pages/api/deposits.ts
- packages/arb-token-bridge-ui/src/pages/api/withdrawals.ts
- packages/arb-token-bridge-ui/src/util/cctp/fetchCCTP.ts
- packages/arb-token-bridge-ui/src/util/deposits/fetchDepositsFromSubgraph.ts
- packages/arb-token-bridge-ui/src/util/withdrawals/fetchWithdrawalsFromSubgraph.ts
We currently get 4x 500 errors on each user session start. This PR fixes that by validating the `pageSize` and having an early return, to avoid subgraph error.
> fix: early return on empty api results

- packages/arb-token-bridge-ui/src/hooks/useETHPrice.ts
no API key, no auth
https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-prices#get-spot-price
https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/rate-limiting
rate limit is 10K calls/hour
This PR changes the refresh interval form every 30s to every 5 mins
Closes #1441
> chore: use Coinbase API for ETH price

- packages/arb-token-bridge-ui/tests/e2e/specfiles.json
- packages/arb-token-bridge-ui/tests/e2e/specs/importToken.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/urlQueryParam.cy.ts
- packages/arb-token-bridge-ui/tests/support/common.ts
It was observed by the team that we were running into a race condition while testing with query params in E2E. This PR just adds a delay for the Bridge UI to settle, and then visits the required URL for testing.
> fix: e2e testing patch

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistory.tsx
- packages/arb-token-bridge-ui/src/hooks/CCTP/useUpdateUSDCBalances.ts
- packages/arb-token-bridge-ui/src/hooks/useAccountIsBlocked.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
- packages/arb-token-bridge-ui/src/pages/api/cctp/[type].ts
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/arb-token-bridge-ui/src/state/cctpState.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/BridgeTransferStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/CctpTransferStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/cctp.ts
- packages/arb-token-bridge-ui/src/util/AddressUtils.ts
- packages/arb-token-bridge-ui/src/util/WithdrawalUtils.ts
- packages/arb-token-bridge-ui/src/util/cctp/getAttestationHashAndMessageFromReceipt.ts
We use it everywhere and I use it a lot in the new tx history. Would be nice to merge it separately to reduce overall diff
> refactor: create `Address` type alias

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableClaimableRow.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableRowAction.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/helpers.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/arb-token-bridge-ui/src/state/app/utils.ts
- packages/arb-token-bridge-ui/src/state/cctpState.ts
Adds `sourceChainId` and `destinationChainId` to `MergedTransaction` so we don't have to do either:
- `tx.isWithdrawal ? tx.parentChainId : tx.childChainId` or,
- cctp: `isEthereumSourceChain : tx.parentChainId : tx.childChainId`
We can just call `tx.sourceChainId/destinationChainId` directly. 
Also reduces diff in the tx history reskin.
> refactor: add `sourceChainId` and `destinationChainId` to tx

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
This PR removes the annoying loading state here
> feat: remove tx summary loader

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistoryTable.tsx
- packages/arb-token-bridge-ui/src/components/common/AddCustomChain.tsx
- packages/arb-token-bridge-ui/src/hooks/__tests__/helpers.ts
- packages/arb-token-bridge-ui/src/hooks/__tests__/useArbQueryParams.test.ts
- packages/arb-token-bridge-ui/src/hooks/__tests__/useNetworks.test.ts
- packages/arb-token-bridge-ui/src/hooks/useNativeCurrency.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
- packages/arb-token-bridge-ui/src/pages/index.tsx
- packages/arb-token-bridge-ui/src/util/EthDepositUtils.ts
- packages/arb-token-bridge-ui/src/util/__tests__/networks.test.ts
- packages/arb-token-bridge-ui/src/util/fetchL2Gateways.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
- packages/arb-token-bridge-ui/src/util/orbitChainsList.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/txHistory.cy.ts
- yarn.lock
Bumps the version of `@arbitrum/sdk` to `3.2.0-custom-fee-token.0` which is the latest stable release with additional (unstable) custom gas token changes on top. The custom gas token changes should land in a stable release soon. 
Everything should work exactly the same.
> refactor: bump @arbitrum/sdk

- packages/arb-token-bridge-ui/src/components/MainContent/MainContent.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistory.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistoryTable.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableRow.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableRowAction.tsx
- Right padding in each row, so that scrollbar doesn't overlap See Details button
- All action buttons same width and text color
- Bottom padding to the entire table
- Lower padding between table header and its bottom border
- Add transparent bottom border to unselected tabs so that they don't "jump" on selection
> fix: tx history improvements in the preview

- packages/arb-token-bridge-ui/src/components/TransferPanel/EstimatedGas.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenDepositCheckDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/hooks.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/components/common/TokenSymbolWithExplorerLink.tsx
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
currently on prod, when user has selected Arb One Native USDC when trying to deposit to an Orbit chain, the balances do not load and the token name is wrong
This PR fixes it
> fix: show USDC names correctly on orbit chain pairs

- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/util/TokenDepositUtils.ts
Reverts OffchainLabs/arbitrum-token-bridge#1540
as infura is now on `nitro/v2.3.0-3e14543/linux-amd64/go1.20.14`
you can use `cast client --rpc-url=` to check
https://book.getfoundry.sh/reference/cast/cast-client
> revert: remove hardcoded retryable gas limit

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableClaimableRow.tsx
> fix: adjust switch network button layout

- packages/arb-token-bridge-ui/src/util/L2ApprovalUtils.ts
`MOON`
https://nova.arbiscan.io/token/0x0057ac2d777797d31cd3f8f13bf5e927571d6ad0
https://etherscan.io/token/0xb2490e357980ce57bf5745e181e537a64eb367b1
As `MOON` is an early token, it didn't implement the `IArbToken` interface and hence requires approval on Arb Nova for the gateway to spend it for bridging.
> feat: add Moon to L2 approval list

- audit-ci.jsonc
We don't use the `Proxy-Authentication` header. So the audit warning can be safely ignored
> chore: update advisories allowlist

- packages/arb-token-bridge-ui/package.json
- yarn.lock
Bumping to include https://github.com/OffchainLabs/arbitrum-sdk/pull/436 which increases the default retryable gas limit increase.
> feat: bump @arbitrum/sdk to v3.3.3

- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useGasSummary.ts
- packages/arb-token-bridge-ui/src/hooks/useTokenToBeBridgedBalance.ts
This bugfix is for
the gas estimation for native gas token deposits from an L2 to the custom gas Orbit chain
when the user's wallet has a higher native gas token amount than their ETH amount on L2
Latest commit on master branch:
https://arbitrum-token-bridge-aazi9ikl8-offchain-labs.vercel.app/?destinationChain=arbitrum-one&sourceChain=ethereum
This PR:
> fix: get correct token balance for orbit deposits

- yarn.lock
Raising https://github.com/OffchainLabs/arbitrum-token-bridge/pull/1608 again so that CI passes and removing ledger patch in yarn.lock
> build(deps): bump express from 4.18.2 to 4.19.2

- packages/arb-token-bridge-ui/src/pages/api/chains/[chainId]/block-number.ts
- packages/arb-token-bridge-ui/src/pages/api/chains/[chain]/block-number.ts
- packages/arb-token-bridge-ui/src/util/SubgraphUtils.ts
- packages/arb-token-bridge-ui/src/util/deposits/fetchDeposits.ts
- packages/arb-token-bridge-ui/src/util/deposits/fetchDepositsFromSubgraph.ts
- packages/arb-token-bridge-ui/src/util/withdrawals/fetchWithdrawals.ts
We want to move all subgraph-related code and network requests to the server (see https://github.com/OffchainLabs/arbitrum-token-bridge/pull/1614) to not leak any API keys and to reduce the client bundle size. 
This PR sets stuff up for https://github.com/OffchainLabs/arbitrum-token-bridge/pull/1614 by adding a new API route `/api/chains/[chainId]/block-number` which returns the latest subgraph-indexed block number for that chain. If there is no subgraph for the chain, it will return 0. The API route follows a REST pattern, and I think we should move the transaction history routes to a similar one soon.
Previously, we were fetching this data from the client directly to the subgraph, but now we fetch it through the API route, so the request is done on the server.
Everything should work …
> feat: fetch latest subgraph block number on the server

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useGasSummary.ts
- packages/arb-token-bridge-ui/src/util/NumberUtils.ts
Currently on production, if the number of decimals of `amount` is more than the number of decimals of the token, the app will crash. This PR fixes it.
> fix: amount overflow error (hotfix)

- packages/arb-token-bridge-ui/src/hooks/useAccountType.ts
- packages/arb-token-bridge-ui/src/util/AddressUtils.ts
There was an issue where Safe wallet connection was not being detected as Smart Contract Wallet in Bridge UI.
Cause: 
When we use `const provider = useProvider()`  it sends both, the source chain and destination chain providers to the `addressIsSmartContract`  function. 
Now the catch is, when we log in to safe, we only log in through one of the providers (ie. either Ethereum or Arbitrum One, depending on the nature of SCW we created), so the other provider, when passed into the hook, results in the `addressIsSmartContract` value as false, and overrides the original true value from the correct provider.
Instead, now we pass just the source-chain-provider and it works consistently for testnets and mainnets.
> fix: smart-contract wallet detection fix

- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20WithdrawalStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/EthWithdrawalStarter.ts
This was missed with the token bridge sdk, but was in previously.
Before:
- ETH withdrawal gas limit: ~70k
- WETH withdrawal gas limit: ~167k
After:
- ETH withdrawal gas limit: ~90k
- WETH withdrawal gas limit: ~217k
> fix: increase withdrawals gas limit by 30%

- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20DepositStarter.ts
- packages/arb-token-bridge-ui/src/util/TokenDepositUtils.ts
We observed a few transactions (especially in Orbit deposits) when the first time token deposits took ~6x the originally estimated gas.
> fix: hardcode higher gas limit for first time deposits

- packages/arb-token-bridge-ui/src/util/TokenDepositUtils.ts
We observed [this tx](https://arbiscan.io/tx/0x8f52daffdd97af8130d667a74a89234cd9ce838d23214d61818bd9743a2f64f8) to be taking more gas than what we estimate on UI. 
Updating the fallback gas limit for token deposits to accommodate for this case as well.
> fix: bump hardcoded retryable gas limit for deposits

- packages/arb-token-bridge-ui/src/components/common/AddCustomChain.tsx
- packages/arb-token-bridge-ui/src/hooks/useNetworks.ts
- packages/arb-token-bridge-ui/src/hooks/useRedeemRetryable.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/BridgeTransferStarterFactory.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/utils.ts
Teleport PR 1 of n.
---
We use `getProviderFromChainId` all over the code, in `token-bridge-sdk` and UI as well. It's better if this method is exported from `token-bridge-sdk`, rather than us trying to import this method from UI into SDK.
Closes FS-537
> refactor: move `getProviderFromChainId` into `bridge-sdk`

- .github/workflows/orbit-retryable-monitor.yml
- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/scripts/generateOrbitChainsToMonitor.ts
Scripts to monitor all the retryables for Orbit chains that have been added to the Bridge UI. They will run daily and will alert us in the testing channel. The steps are as follows: 
1. Using Github actions - Generate the `Orbit chains' json` that is compatible with the input for https://github.com/OffchainLabs/orbit-retryable-tracker script.
2. Move the generated `orbit-chains' json` to the config of `orbit-retryable-tracker` script, and run the `findRetryable` script in that repo.
3. Raise alerts about any unsuccessful retryables found in the chains.
Closes FS-525
> feat: monitor orbit retryables

- .github/workflows/orbit-retryable-monitor.yml
We need `Monitor Orbit Retryables` action to checkout the main branch instead of the branch which got deleted after the merge.
> fix: update orbit-retryables monitoring branch

- .github/workflows/orbit-retryable-monitor.yml
With this, we will be able to run the `Orbit Retryable Monitoring` action manually, without waiting for cron-job to trigger it
> ci: add manual trigger to orbit retryables monitor

- packages/arb-token-bridge-ui/package.json
- yarn.lock
Updates `@arbitrum/sdk` to the latest teleporter tag `3.4.1-teleporter.2` that has some fixes.
> chore: update `@arbitrum/sdk`

- .github/workflows/orbit-retryable-monitor.yml
To be merged after https://github.com/OffchainLabs/orbit-retryable-tracker/pull/7 is merged
> chore: update branch for orbit-retryable monitor

- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
With teleport now we have chain pairs L1<>L3. We have to early return for this case because otherwise the code will progress to fetching withdrawals. It would fetch withdrawals for L3 and set the parent chain as L1.
> fix: dont fetch withdrawals for teleport pairs

- packages/arb-token-bridge-ui/src/components/TransferPanel/AdvancedSettings.tsx
- packages/arb-token-bridge-ui/src/hooks/useAccountType.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20WithdrawalStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/teleport.ts
- packages/arb-token-bridge-ui/src/util/AddressUtils.ts
- packages/arb-token-bridge-ui/src/util/TokenDepositUtils.ts
We should use the wallet's chain instead of the source chain for detecting if the wallet is a Smart Contract Wallet.
> fix: detect SCW correctly

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
Banner shows when user's source/destination chain is either Stylus testnet v1 or v2
Closes FS-606
> feat: add Stylus testnet warning banner

- .github/workflows/build-test.yml
GA is masking secrets so setting booleans from secrets messes up env vars.
> ci: hardcode graph network enabled flag

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20TeleportStarter.ts
- yarn.lock
Bumps `@arbitrum/sdk` to the latest, and handles teleporter changes.
> chore: bump @arbitrum/sdk and refactor teleporter code

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferDisabledDialog.tsx
- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
When user tries to select GHO to deposit from Ethereum to Arbitrum One, the withdraw-only dialog pops up and suggests the CCIP bridge link. https://app.transporter.io/?from=mainnet&tab=token&to=arbitrum&token=GHO
Closes FS-648
> feat: add GHO to withdraw-only list

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/hooks/useNetworks.ts
- packages/arb-token-bridge-ui/src/types/ChainQueryParam.ts
- packages/arb-token-bridge-ui/src/util/TokenTeleportEnabledUtils.ts
- packages/arb-token-bridge-ui/src/util/__tests__/networks.test.ts
- packages/arb-token-bridge-ui/src/util/bridgeUiConfig.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
- packages/arb-token-bridge-ui/src/util/orbitChainsList.ts
- packages/arb-token-bridge-ui/src/util/wagmi/getWagmiChain.ts
- packages/arb-token-bridge-ui/src/util/wagmi/setup.ts
- packages/arb-token-bridge-ui/src/util/wagmi/wagmiAdditionalNetworks.ts
- yarn.lock
> feat: remove stylus testnet v2 and update @arbitrum/sdk

- packages/arb-token-bridge-ui/src/hooks/useBalance.ts
Fixes an issue with `useBalances` where passing any destination address would retrigger fetching, even if the address is not valid. This also caused flakiness in ERC20 deposit and withdrawal e2e.
Before:
On prod you should see `useBalance` retrigger in the network tab with each character typed in the custom destination address.
After:
`useBalance` updates only when the custom destination address is complete and valid.
> fix: fetch balances when wallet address is valid

- packages/arb-token-bridge-ui/src/components/TransactionHistory/helpers.ts
Fixed the logic for fetching and updating withdrawal status in tx history - otherwise, it was not activating the `Claim` button even if the withdrawal status would change into `Confirmed`.
This also explains why the Claim button wouldn't get activated while tx history was kept open - but would activate when the page was refreshed.
> fix: withdrawal status updates in tx history

- packages/arb-token-bridge-ui/scripts/generateCoreChainsToMonitor.ts
Github secrets return `''` for empty values, so we need to sanitize the value before falling back to original RPCs
Successful run here - https://github.com/OffchainLabs/arbitrum-token-bridge/actions/runs/10181962577/job/28163373599
> fix: sanitize env variables for batch poster monitoring

- packages/arb-token-bridge-ui/src/state/app/utils.ts
On load teleport txs would show in pending tab even if completed. After a few moments updater would update them correctly.
This fixes the initial status
> fix: fetch correct teleport status on initial load

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
Caused USDC not being selectable on Orbit chains if token bridge was undefined
> fix: allow USDC selection if token bridge not loaded

- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useGasSummary.ts
> refactor: clean up gas summary code

- packages/arb-token-bridge-ui/src/util/TokenTeleportEnabledUtils.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
Note: only ETH and WETH have been allowlisted, since USDC is not supported for LayerLeap transfers yet.
[Tested here](https://etherscan.io/tx/0xa5f3e2cbf6c3c55fff85ff740ecf7d373474c7fce66e4438808ca0c13054d70f)
Closes #1826
> feat: enable Layer Leap for Proof of Play Boss

- package.json
- packages/arb-token-bridge-ui/.e2e.env.sample
- packages/arb-token-bridge-ui/src/components/TransferPanel/AdvancedSettings.tsx
- packages/arb-token-bridge-ui/synpress.cctp.config.ts
- packages/arb-token-bridge-ui/synpress.config.ts
- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/getCommonSynpressConfig.ts
- packages/arb-token-bridge-ui/tests/e2e/specfiles.json
- packages/arb-token-bridge-ui/tests/e2e/specs/approveToken.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
- packages/arb-token-bridge-ui/tests/support/common.ts
- packages/arb-token-bridge-ui/tests/support/index.ts
- tsconfig.eslint.json
> test: Add CCTP synpress config

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainInput.tsx
Currently on production, the "Move Funds" button is disabled after a successful transfer because the `amount` query param is cleared after transfer, but the input value is not cleared.
This PR synchronises the input value with the query param.
> fix: re-enable move funds button after transfer

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/DestinationNetworkBox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/SourceNetworkBox.tsx
- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useIsBatchTransferSupported.ts
Some improvements from https://www.notion.so/arbitrum/Batched-ERC20-ETH-transfers-0df3704c9aef464cb443c0b97d852465
- Disable for CCTP
- Reset input when selected token would not be supported
- Only keep “You can transfer ETH in the same transaction if you wish to.” text under the input.
- Clear extra ETH amount when extra ETH input is not visible
- Show ETH balance on the destination chain for batched transfers
> feat: batch transfer improvements

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/DestinationNetworkBox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/SourceNetworkBox.tsx
Before we'd show native currency balance on the destination chain only if `amount2` is greater than 0. It's because we didn't have access to the state so we use zustand now.
Before - ETH balance not showing because `amount2` is not set:
After - ETH balance showing because the `amount2` input is shown, regardless of its value:
> fix: show balance when amount2 input is visible

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/SourceNetworkBox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainInput.tsx
If balance is 0 it would read the condition as `false` and display a loader
> fix: show correct balance for batch transfers

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenImportDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferDisabledDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainInput.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/hooks/useSelectedTokenIsWithdrawOnly.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
Closes FS-850
This PR utilises the OFT method that LayerZero tokens inherit to identify if they are a LayerZero token.
By default all tokens utilising the LayerZero implementation are withdraw-only on our bridge.
Example: 
ZRO https://etherscan.io/token/0x6985884c4392d348587b19cb9eaaf157f13271cd
The `oftVersion()` is only availalbe on LayerZero v2 contract so legacy tokens will not be detected, as they implemented https://github.com/LayerZero-Labs/endpoint-v1-solidity-examples/blob/main/contracts/token/oft/v1/OFT.sol
e.g. GSWIFT https://etherscan.io/address/0x580e933d90091b9ce380740e3a4a39c67eb85b4c
> feat: autodetect LayerZero tokens

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
> refactor: use source chain signer

- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
> fix: update unite chain color

- packages/arb-token-bridge-ui/src/util/networks.ts
- packages/arb-token-bridge-ui/src/util/networksNitroTestnode.ts
- packages/arb-token-bridge-ui/synpress.config.ts
- packages/arb-token-bridge-ui/tests/support/common.ts
The cypress command files are not prebuilt, but are run when the Cypress window opens and are compiled then. The source file `/support/common.ts` imports from `networks.ts` which eagerly requires env variables with `loadEnvironmentVariableWithFallback` for `rpcURLs`, but the env variables are empty.
This becomes a problem with https://github.com/OffchainLabs/arbitrum-token-bridge/pull/2107 once loading env variables is a bit more strict.
Really, the cypress command files shouldn't import from source code, but that's a bigger topic.
> refactor: move nitro testnode networks to new file

- packages/arb-token-bridge-ui/src/components/TransactionHistory/useTransactionReminderInfo.ts
Currently we show the tx history banner for the connected address even when the user is searching another address on tx history
This PR shows the relevant tx history banner for the searched address instead
Closes FS-1095
> feat: show relevant address tx history banner

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
closes FS-998
Try to deposit USDC (through Arbitrum bridge, not CCTP). The transfer button loading state will reset as soon as you confirm the USDC dialog.
This happened because [here](https://github.com/OffchainLabs/arbitrum-token-bridge/blob/master/packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx#L422) we await `depositToken` but the transfer method wasn't returned, so it jumped to finally block and set transferring to false.
> fix: show transfer button loader for USDC.e deposits

- .github/workflows/test.yml
@spsjvc mentioned that everything is checked when it's still a PR, so we shouldn't need to run tests again when it's merged into master
For the change, see https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs
> ci: don't run tests on master branch

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/DestinationNetworkBox.tsx
Below the old version, loader misaligned
> fix: fix balance loader alignment

- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
The RPC and explorer URLs for Plume were incorrectly pointed to an old version of the network.
> fix: update Plume RPC and explorer URLs

- yarn.lock
Running `yarn install` against the current files results in some changes
Updating `yarn.lock` to allow correct deps versions esp multiple versions of the same deps.
> build(deps): update yarn.lock with latest octokit versions

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/common/Dialog2.tsx
- packages/arb-token-bridge-ui/src/components/common/NewDialog.tsx
Note we move 2-3 dialogs at a time, opened more PRs
> refactor: move dialogs to a single component (part 1)

- package.json
- yarn.lock
https://github.com/advisories/GHSA-968p-4wvh-cqc8
- react-virtualized: no patch on their end
- @rainbow-me/rainbowkit: requires major version bump on our end
- wagmi: requires major version bump on our end
> chore(deps): bump babel/runtime

- package.json
- packages/arb-token-bridge-ui/package.json
- yarn.lock
This is an effort to resolve Sentry error messages which are potentially wrong/missing error messages coming from ethers v5
see https://github.com/ethers-io/ethers.js/issues/2603#issuecomment-1079646891
We are 2 minor versions behind the legacy ethers v5 so bumping it *might* help
By bumping the package, we can also remove some resolutions in `package.json`
Related ticket: FS-982
> build: bump ethers to latest of v5

- packages/arb-token-bridge-ui/package.json
- yarn.lock
Bumping due to https://nextjs.org/blog/cve-2025-29927, even though we shouldn't be affected
> build(deps): bump next from 14.2.22 to 14.2.25

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts
- packages/arb-token-bridge-ui/src/hooks/useSelectedToken.ts
When L2 address is found in the token lists, we use its data to also set L1 address for the token: https://github.com/OffchainLabs/arbitrum-token-bridge/blob/master/packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts#L87-L119
Because L2's USDC name is "Bridged USDC", it sets it as L1 token name in our list.
So we need to apply USDC first.
> fix: return usdc token before token lists token

- packages/arb-token-bridge-ui/src/hooks/useOftTransactionHistory.ts
LayerZero API returns 404 if no transactions are found, but SWR considers it as an API error, and retries by default. This results in `Loading Transactions` popping up in periodically.
> fix: skip retries for LayerZero API 404 response

- packages/arb-token-bridge-ui/src/components/TransferPanel/Routes/CctpRoute.tsx
Right now if you run the app locally and select the CCTP route for USDC, the app would crash.
> refactor: import shallow correctly into CctpRoute

- packages/arb-token-bridge-ui/package.json
- yarn.lock
doesn't seem like we used any methods from the SDK that requires migration
migration doc from v8 to v9:
https://docs.sentry.io/platforms/javascript/guides/react/migration/v8-to-v9/
> build(deps): bump sentry

- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawNativeToken.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
Signer can be undefined for the first few renders as the claim button shows. In e2e we click it instantly which causes a failure on occasion
> test: add `clickClaimButton` method to e2e

- packages/arb-token-bridge-ui/src/components/TransactionHistory/EmptyTransactionHistory.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistorySearchResults.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableRowAction.tsx
- packages/arb-token-bridge-ui/src/hooks/useAccountType.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
1. Removed "Load more" button for no connected wallet.
2. Removed not needed content from `EmptyTransactionHistory` for no connected wallet.
3. Fixed fetching for searched address for no connected wallet.
4. Added "Connect" button for claiming and retrying for no connected wallet.
Closes FS-1211
> fix: tx history fixes for no wallet connection

- packages/arb-token-bridge-ui/src/hooks/useOftTransactionHistory.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/oftUtils.ts
LayerZero API returns the list of ALL messages related to the user's wallet, regardless of whether they were initiated by the users themselves or through another smart contract/protocol (eg. Lifi Diamond contract). However, these cases differ in their signatures, and hence fail to be validated properly, and break in our transaction history, resulting in errors as reported by one of our users.
This PR enhances the validation logic and ensures that the payload is properly decodable by the intended ABIs before proceeding to show these transactions in the UI.
> fix: enhance layerzero message validation

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/App/AppProviders.tsx
- packages/arb-token-bridge-ui/src/pages/_app.tsx
The PR extracts provider-related code currently scattered in `App.tsx` into a new wrapper component called `AppProviders.tsx`
Also, it moves the `Layout` component out from NextJs managed `_app`, to `App.tsx` managed by us. This is because in order to ship responsive embed-mode later, we will need the common `Layout` to be conditionally rendered based on the query params being passed to it.
> refactor: organize `AppProviders` and `Layout`

- packages/arb-token-bridge-ui/src/util/deposits/helpers.ts
Fix teleport transaction status handling by reordering status checks to prioritize teleport validation before parent-child message checks. This prevents early returns for valid teleport transactions that don't emit `parentToChildMsg` events. Also improves code comments for better maintainability.
> fix: teleport tx history

- .github/workflows/monitoring.yml
This PR passes Notion-related env variables for the upcoming Retryable monitoring improvements
> ci: add notion env variables for monitoring

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/ui-driver/UiDriver.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriverCctp.test.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriverCctp.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriverCommon.ts
<table><tr><td><details><summary>This PR is part of a stack created with <a href="https://github.com/aviator-co/av">Aviator</a>.</summary>
* **#2526**
* **#2525**
* **#2524**
* **#2523**
* **#2522**
* ➡️ **#2521**
* `master`
> refactor: rename ui driver step type

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/ui-driver/UiDriver.test.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriver.ts
<table><tr><td><details><summary>This PR is part of a stack created with <a href="https://github.com/aviator-co/av">Aviator</a>.</summary>
* **#2526**
* **#2525**
* **#2524**
* **#2523**
* ➡️ **#2522**
* `master`
> refactor: pass in ui driver context to executor

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
- yarn.lock
closes FS-1282
Limits withdrawal batches we fetch in parallel to 10 for specified chains.
1. Go to Performance tab in devtools.
2. Click Record and refresh the page right away.
3. Record the first ~10s as transaction history is loading (no need to wait for the entire history to finish fetching).
4. CTRL/CMD + F and search for: "withdrawal batch start chainId:4078".
5. Iterate through batches and check timestamps. Concurrent fetches of 10 should have around the same timestamp. There may be deviations based on network delays etc but the most important is they don't fetch at the same time.
> feat: limit concurrent batched withdrawals
