- package.json
- yarn.lock
> bump up vector-modal version

- src/components/Actions/ConfirmDialog.tsx
- src/components/Actions/ERC20L1Actions.tsx
- src/components/Actions/ERC20L2Actions.tsx
- src/components/Actions/EthL1Actions.tsx
- src/components/Actions/EthL2Actions.tsx
- src/components/Actions/numberInputForm.tsx
(check out deploy preview in CI below)
> add confirm popups for deposits and withdrawals

- package.json
- src/components/Actions/ERC20L1Actions.tsx
- src/components/PendingWithdrawals/index.tsx
- yarn.lock
uses https://github.com/OffchainLabs/token-bridge-sdk/commit/27ca37b37a19be38bc8905f1e2e1574012381c20
> fix decimals display for pending withdrawals

- src/components/TransferPanel/AmountBox.tsx
- src/components/TransferPanel/NetworkBox.tsx
- src/components/TransferPanel/TransferPanel.tsx
fixes https://github.com/OffchainLabs/arb-token-bridge/issues/72
> disable transfers on improper input values

- src/components/Actions/ERC20L1Actions.tsx
- src/components/Actions/EthL1Actions.tsx
- src/components/App/index.tsx
- src/components/PendingWithdrawals/index.tsx
- src/components/TabsContainer/index.tsx
state gets set/update in App/index.tsx
> add pending withdrawals loading indicator

- src/components/App/App.tsx
- src/components/DisclaimerModal/DisclaimerModal.tsx
- src/components/common/MessageOverlay.tsx
Shows TOS disclaimer on app load. App can't be used without accepting the tos. It stores the value in localstorage so on subsequent loads if TOS is accepted it will not show the disclaimer again.
> TOS disclaimer modal

- src/components/TransactionsTable/TransactionsTable.tsx
- src/components/common/Button.tsx
- src/state/app/state.ts
Implemented Hunter's suggestions
> Improved withdrawal UX

- packages/arb-token-bridge-ui/src/components/syncers/RetryableTxnsIncluder.tsx
- packages/arb-token-bridge-ui/src/state/app/actions.ts
fixes https://github.com/OffchainLabs/arb-token-bridge/issues/131
> use getter for sorted txns in RetryableTxnsIncluder

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useWithdrawOnly.tsx
merge w/ https://github.com/OffchainLabs/arb-token-lists/pull/2
> use lowercase addresses for withdraw only check and warning token check

- packages/arb-token-bridge-ui/public/token-list-42161.json
generated from https://github.com/OffchainLabs/arb-token-lists
note that parens in `name` are now allowed https://github.com/Uniswap/token-lists/commit/6328ebc34d516b8fa4aacf851a908937a574fb2f
> patch token list (update logo uris)

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/util/index.ts
fixes https://github.com/OffchainLabs/arb-token-bridge/issues/190
> show warning when connected as contract

- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
fixes https://github.com/OffchainLabs/arb-token-bridge/issues/159
> update default testnet explorer / add all explorers to dropdown

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
fixes https://github.com/OffchainLabs/arb-token-bridge/issues/151
> better network switch handling; include "add l2 network" button

- packages/arb-token-bridge-ui/public/token-list-42161.json
Reverts OffchainLabs/arb-token-bridge#207
> Revert "update to new uniswap token list format"

- packages/arb-token-bridge-ui/public/token-list-42161.json
fixes https://github.com/OffchainLabs/arb-token-lists/issues/8
> keep l1address / bridge fields in arbitrum OGs list for backwards compatibility

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
Related to https://github.com/OffchainLabs/App_Engineering_-_Docs__PM/issues/2 and https://github.com/OffchainLabs/arb-token-lists/issues/11
> Check the routers are consistent before allowing a deposit

- packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTable.tsx
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- packages/token-bridge-sdk/src/util/graph.ts
testing it against the https://github.com/OffchainLabs/arbitrum-sdk/pull/27/commits/b2bf65abe213187389657e4ec1368cd1b1b64643 build of sdk; i think the only remaining todo is enabling eth withdrawals (which i believe depends on https://github.com/OffchainLabs/arbitrum-sdk/pull/29)
> updates for nitro withdrawals

- packages/arb-token-bridge-ui/src/components/TransferPanel/useL2Approve.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useWithdrawOnly.tsx
Adding some metadata like token symbol and l2 custom address to make the list easier to understand.
> docs: add metadata to special case lists

- packages/arb-token-bridge-ui/src/components/App/App.tsx
> API wallet_switchEthereumChain only works on versions higher than 2.10.0.
https://imtoken.gitbook.io/developers/products/webview/rpcs#wallet_switchethereumchain
And the current version of imToken is 2.10.1.
> feat: allow imToken to call `wallet_switchEthereumChain`

- packages/token-bridge-sdk/package.json
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- yarn.lock
Takes advantage of new functionality in https://github.com/OffchainLabs/arbitrum-sdk/pull/66.
> fix: alert user if eth deposit fails on initiation

- packages/token-bridge-sdk/package.json
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- yarn.lock
Reverts OffchainLabs/arb-token-bridge#323
> Revert "fix: alert user if eth deposit fails on initiation"

- packages/token-bridge-sdk/package.json
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- yarn.lock
cherry-picked the previously reverted PR then version bumped sdk for the fix
> chore: bump sdk version and reapply alert surfacing on deposit fail

- packages/arb-token-bridge-ui/src/components/TransferPanel/useWithdrawOnly.tsx
https://github.com/alchemix-finance/deployments/tree/master/arbitrum
> fix: add Alchemix tokens to withdraw only list

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderConnectWalletButton.tsx
Fixes a couple of small issues that were surfaced on Sentry.
> fix: handle various small issues

- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderMenu.tsx
Making it a tiny bit more DRY.
> refactor: update header menus

- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
This is the cleanest/smallest diff for the `$MKR` fix (only affecting a single method). 
Reading token details from a token list would be a bigger change, so I opted for this one, as it's most likely temporary, anyway.
> fix: add optional overrides for special case ERC-20 tokens

- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
Reverts OffchainLabs/arb-token-bridge#353
> fix: hardcode last outbox entry for rinkeby

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/DepositCardPending.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCardUnconfirmed.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderNetworkInformation.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
In this PR:
* Use network names from our list, making it easier to adjust and the UI more predictable
* Add L2 DAI Gateway address for Arbitrum Nova (https://github.com/OffchainLabs/arb-token-bridge/commit/36fd08ccb9aaa3a5f187daebe65309a5296cde87)
> refactor: read network names from a list

- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
- sort by favorites first, then alphabetically
> feat: sort bridges alphabetically

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
cherry picked the changes from https://github.com/OffchainLabs/arb-token-bridge/pull/344
we might want to update the links we point to
> feat: add arb1 nitro migration maintenance ui

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
They have a custom bridge but not registered to router.
> chore: add emax to withdraw only

- packages/token-bridge-sdk/src/hooks/useTransactions.ts
Fix transactions spelling error
> fix: spelling error in useTransactions

- packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
After the update, the new Network+Signer status looks as follows:
> feat: attach provider objects to `useNetworksAndSigners` result

- packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
`StaticJsonRpcProvider` reduce the number of rpc requests roughly by half
> perf: use StaticJsonRpcProvider

- packages/arb-token-bridge-ui/package.json
- yarn.lock
Tested the involved UIs
Everything seems to work as expected
Closes #315
> chore: update `headlessui` to latest

- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
> fix: lowercase address when adding token

- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/util/networks.ts
Updates explorer URLs both in the UI (header) and in some config files.
> fix: update block explorer urls

- packages/arb-token-bridge-ui/src/components/common/Footer.tsx
> style: change footer "learn more" link font-size

- audit-ci.jsonc
> chore: add new advisory

- .eslintrc.js
- packages/arb-token-bridge-ui/src/components/App/AppContext.tsx
- packages/arb-token-bridge-ui/src/components/TransactionsTable/TransactionsTableWithdrawalRow.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/DepositConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenImportDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalCard.tsx
- packages/arb-token-bridge-ui/src/components/common/Button.tsx
- packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
- packages/arb-token-bridge-ui/src/components/common/Tab.tsx
- packages/arb-token-bridge-ui/src/components/syncers/RetryableTxnsIncluder.tsx
- packages/arb-token-bridge-ui/src/state/app/onInitialize.ts
- packages/arb-token-bridge-ui/src/util/RetryableUtils.ts
- packages/arb-token-bridge-ui/src/util/fastBridges.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
- packages/token-bridge-sdk/src/hooks/__tests__/useBalance.test.tsx
- packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts
- packages/token-bridge-sdk/src/hooks/useBalance.ts
Fix eslint errors preventing `yarn run start_ui` from running
> fix: clean up eslint errors in UI and SDK

- packages/arb-token-bridge-ui/public/index.html
> chore: change page title

- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderMenu.tsx
> style: adjust ecosystem dropdown in header

- yarn.lock
saw this at `yarn build` on github actions
```
$ CI= craco build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
run `npx browserslist@latest --update-db` on master branch
the changes you get should be the same
> build: update browserslist

- vercel.json
Summary
This is to allow external parties to use our token list
https://vercel.com/docs/project-configuration#legacy/routes
Steps to test
set up a minimal app on another origin and fetch https://arb-token-bridge-git-fix-cors-offchain-labs.vercel.app/token-list-42161.json
superseded https://github.com/OffchainLabs/arb-token-bridge/pull/541
> fix: cors using routes

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
> fix: nova background image not loaded correctly

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
Relay Token is bridged by relaychain themself and not by our bridge, its l2 address should be 0x1426CF37CAA89628C4DA2864e40cF75E6d66Ac6b.
We can see it at https://bridge.relaychain.com/bridge when choose relay token and click `copy the destination token address`.
> fix: add relay token to withdrawOnly List

- packages/arb-token-bridge-ui/src/util/index.ts
https://github.com/OffchainLabs/arb-token-bridge/issues/566
> refactor: make `loadEnvironmentVariableWithFallback` always return a string

- .github/workflows/build-test.yml
Add checkout repo action before using `node-modules/install` action, so cache-key is properly computed
> ci: add checkout to install job

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainInput.tsx
- packages/arb-token-bridge-ui/src/hooks/__tests__/useArbQueryParams.test.ts
- packages/arb-token-bridge-ui/src/hooks/useArbQueryParams.tsx
- packages/arb-token-bridge-ui/synpress.config.ts
Users can now use either dot or comma notation for decimal.
With browser set in any language, entering either 'X.Y' in token amount should work correctly. Number should be displayed with dot notation. URL should be set accordingly.
When refreshing, input should have the value set according to URL.
> fix: input localization

- packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
- packages/arb-token-bridge-ui/src/pages/api/screen.ts
We don't want to require screening .env variables for local development.  But we want to make sure those variables are set for production environment
> fix: don't screen addresses in development

- packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
also removed `ArbitrumBetaNotification`
> feat: add banner

- audit-ci.jsonc
Updates `audit-ci.jsonc` to ignore `GHSA-p8p7-x288-28g6`.
N/A
> chore: update audit-ci.jsonc

- packages/arb-token-bridge-ui/tests/e2e/specs/txHistory.cy.ts
Fixed failing tests for tx-history after changing the schema of Tabs
> fix: update tx history e2e tests

- packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
- packages/arb-token-bridge-ui/src/components/syncers/ThemeIncluder.tsx
- packages/arb-token-bridge-ui/src/styles/purple.css
The classic theme will stay available
> chore: turn off april fools after midnight

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/App/WelcomeDialog.tsx
- packages/arb-token-bridge-ui/src/components/common/Dialog.tsx
- packages/arb-token-bridge-ui/src/components/common/Layout.tsx
- packages/arb-token-bridge-ui/src/constants.ts
- packages/arb-token-bridge-ui/src/hooks/useNetworksAndSigners.tsx
> fix: only show connect modal after TOS is accepted

- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderAccountPopover.tsx
- packages/arb-token-bridge-ui/src/components/common/HeaderNetworkNotSupported.tsx
- packages/arb-token-bridge-ui/src/util/wagmi/setup.ts
Closes #676 
Completes all requirements in #676 thread
- Add disconnect wallet to wrong network UI
- Update `Wrong Network` button sizing to be more consistent
> feat: add disconnect wallet button to wrong network ui

- packages/arb-token-bridge-ui/src/pages/_document.tsx
Context: https://usefathom.com/changelog#mar2023
> chore: update fathom script src

- packages/arb-token-bridge-ui/src/hooks/useDeposits.ts
- packages/arb-token-bridge-ui/src/hooks/useWithdrawals.ts
> fix: unwanted tx history reload on network change

- packages/arb-token-bridge-ui/src/__test__/tokenLists.test.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearchUtils.ts
- packages/arb-token-bridge-ui/src/components/syncers/TokenListSyncer.tsx
- packages/arb-token-bridge-ui/src/hooks/useTokenLists.ts
- packages/arb-token-bridge-ui/src/util/TokenListUtils.ts
> refactor: move tokenLists.tsx into hooks and utils

- packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
Update "What is Nitro Testnet?" link to [https://developer.arbitrum.io/for-devs/troubleshooting-building#what-is-a-testnet-or-a-devnet](https://developer.arbitrum.io/for-devs/troubleshooting-building#what-is-a-testnet-or-a-devnet)
> feat: Update "What is Nitro Testnet?" link

- packages/arb-token-bridge-ui/src/components/App/BlockedDialog.tsx
> chore: replace support email with ticket link

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> chore: add tBTC to withdraw-only list

- packages/arb-token-bridge-ui/package.json
- yarn.lock
From release summaries, the changes are mostly locale name and format accuracy
https://github.com/iamkun/dayjs/releases
Closes #718
> chore: update dayjs to latest

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenRow.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
to increase readability and maintainability
> chore: move token row to its own file

- packages/arb-token-bridge-ui/src/components/TransferPanel/AdvancedSettings.tsx
> fix: remove duplicate `useEffect`

- packages/arb-token-bridge-ui/src/components/TransactionHistory/PendingDepositWarning.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/PendingTransactions.tsx
- packages/arb-token-bridge-ui/src/state/app/utils.ts
Only show when user has pending deposits
Toggle to show more info
> feat: tell users to stay on page during deposit

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
> fix: right align balance on `TransferPanel`

- packages/arb-token-bridge-ui/src/components/common/Layout.tsx
> chore: update banner text

- packages/arb-token-bridge-ui/src/components/TransferPanel/NetworkListbox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/OneNovaTransferDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
Closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/1039
> feat: show dialog for transfers between one and nova

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCDeposit/USDCDepositConfirmationDialogCheckbox.tsx
- packages/arb-token-bridge-ui/src/constants.ts
- packages/arb-token-bridge-ui/src/util/fastBridges.ts
Specs: https://github.com/OffchainLabs/arbitrum-token-bridge/issues/1051
> chore: update USDC Learn more link

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCWithdrawal/USDCWithdrawalConfirmationDialog.tsx
- yarn.lock
Fix error with `eslint-config-prettier` missing when running `yarn lint`
> ESLint couldn't find the config "prettier" to extend from. Please check that the name of the config is correct.
`yarn lint` should now run without error
> chore: Add eslint-config-prettier

- .github/ISSUE_TEMPLATE/config.yml
- packages/arb-token-bridge-ui/src/components/App/App.tsx
- packages/arb-token-bridge-ui/src/components/App/BlockedDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/LowBalanceDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/WithdrawalConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/constants.ts
> chore: update zendesk link

- packages/arb-token-bridge-ui/src/constants.ts
> chore: remove prefilled info from zendesk link

- packages/arb-token-bridge-ui/src/components/TransactionHistory/PendingDepositWarning.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenDepositCheckDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/common/Footer.tsx
- packages/arb-token-bridge-ui/src/components/common/Header.tsx
- packages/arb-token-bridge-ui/src/components/common/Layout.tsx
- packages/arb-token-bridge-ui/src/components/common/Notifications.tsx
- packages/arb-token-bridge-ui/src/constants.ts
Raising a PR, as Dragisa suggested (😆), to update the links to the docs so they point to the latest domain.
> chore: update links to docs

- packages/arb-token-bridge-ui/src/hooks/CCTP/useCCTP.ts
Add headers to `fetch` when fetching CCTP attestation
> fix: add headers to CCTP attestation fetching

- README.md
- packages/arb-token-bridge-ui/src/pages/api/cctp/[type].ts
- packages/arb-token-bridge-ui/src/util/wagmi/setup.ts
- Updates local setup instructions to include `NEXT_PUBLIC_CCTP_SUBGRAPH_BASE_URL`
- Makes `NEXT_PUBLIC_CCTP_SUBGRAPH_BASE_URL` optional
> chore: update local setup instructions

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
> chore: use isUserRejection to check tx error

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/components/common/Checkbox.tsx
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
> chore: update copy on approval dialog

- audit-ci.jsonc
Update allowlist for audit securities to include https://github.com/advisories/GHSA-m95q-7qp3-xv42
> chore: Update audit allowlist

- packages/arb-token-bridge-ui/src/pages/geofence.tsx
- packages/arb-token-bridge-ui/src/pages/restricted.tsx
The page can be accessed directly at https://arbitrum-token-bridge-git-geofence-offchain-labs.vercel.app/restricted
> feat: geofence page

- packages/arb-token-bridge-ui/package.json
- yarn.lock
this fixes https://github.com/OffchainLabs/arbitrum-token-bridge/security/dependabot/142
> chore: bump next

- .github/workflows/build-test.yml
the Build, Test github action will rerun automatically when PR title is changed
closes #875
> ci: don't run e2e for hotfix PRs

- packages/arb-token-bridge-ui/src/components/TransactionHistory/PendingTransactions.tsx
> chore: add the graph maintenance msg to tx history

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelUtils.ts
- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useConnectionState.ts
- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useImportTokenModal.ts
- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useStyles.ts
- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useSummaryVisibility.ts
this PR reduces lines of code in `TransferPanel` by moving some code into custom hooks or utils files
> refactor: move some code from tx panel to custom hooks

- packages/arb-token-bridge-ui/src/components/common/AddCustomChain.tsx
It was treating zero address as a custom fee token instead of ETH.
> fix: treat native token zero address as ether

- packages/arb-token-bridge-ui/package.json
- yarn.lock
> chore: bump @arbitrum/sdk

- packages/arb-token-bridge-ui/src/util/networks.ts
> chore: remove rinkeby from codebase

- packages/arb-token-bridge-ui/src/components/TransactionHistory/PendingTransactions.tsx
> feat: remove subgraph message banner

- packages/arb-token-bridge-ui/src/components/common/AddCustomChain.tsx
**Note: This is NOT backward compatible. You'll have to add your chain again to be able to download the Orbit config.**
When downloading the custom chain config, users download chain details which is used for adding the custom network. This is not very useful.
Now users will download the orbit config generated in the orbit setup script.
I decided to add a new storage key and store the Orbit config data separately, because there was extra complexity if we wanted to completely replace the previous caching.
> fix: download orbit config from orbit setup script

- .github/workflows/build-test.yml
> ci: cancel in progress runs at new commits

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadinessUtils.ts
- packages/arb-token-bridge-ui/src/util/TokenTransferDisabledUtils.ts
> feat: disable rDPX bridging

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
Production
This PR
closes #1267
> feat: only allow relevant network options

- packages/arb-token-bridge-ui/package.json
- yarn.lock
> build: update tailwind merge

- .github/workflows/build-test.yml
> ci: update test-e2e-success job conditions

- packages/arb-token-bridge-ui/src/components/common/Layout.tsx
- packages/arb-token-bridge-ui/src/components/common/WalletConnectWarning.tsx
> feat: add warning for ledger

- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
> feat: increase retryable gas limit for token deposit tx

- packages/arb-token-bridge-ui/src/hooks/arbTokenBridge.types.ts
- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactions.ts
- packages/arb-token-bridge-ui/src/state/app/actions.ts
- packages/arb-token-bridge-ui/src/state/app/state.ts
Removed a lot of unused state variables and types that did not make sense after new tx history
> refactor: remove unused state and types

- packages/arb-token-bridge-ui/scripts/generateDenylist.ts
- packages/arb-token-bridge-ui/src/util/TokenListUtils.ts
> feat: add sepolia token list

- packages/arb-token-bridge-ui/package.json
- yarn.lock
bump axios to fix `follow-redirects` ver that is a new advisory
https://github.com/advisories/GHSA-jchw-25xp-jwwc
> build: bump axios

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
Add GSWIFT token to withdraw only list
(withdraw should still be enabled)
> fix: Add GSWIFT token to withdraw only list

- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
> fix: update key in useTransactionHistory

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenRow.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCDeposit/USDCDepositConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCDeposit/USDCDepositConfirmationDialogCheckbox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCWithdrawal/USDCWithdrawalConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCWithdrawal/USDCWithdrawalConfirmationDialogCheckbox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
- packages/arb-token-bridge-ui/src/hooks/CCTP/useCCTP.ts
- packages/arb-token-bridge-ui/src/hooks/CCTP/useUpdateUSDCBalances.ts
- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
- packages/arb-token-bridge-ui/src/pages/api/cctp/[type].ts
- packages/arb-token-bridge-ui/src/state/cctpState.ts
- packages/arb-token-bridge-ui/src/util/CommonAddressUtils.ts
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
- packages/arb-token-bridge-ui/synpress.config.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
- packages/arb-token-bridge-ui/tests/support/common.ts
Migrated CCTP (USDC) Transfers from Goerli to Sepolia
> feat: migrate cctp transfers from goerli to sepolia

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/token-bridge-sdk/CctpTransferStarter.ts
> fix: Pass destinationAddress to cctpTransfer

- packages/arb-token-bridge-ui/src/components/TransferPanel/NetworkListbox.tsx
> feat: set max height to network listbox

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionStatusInfo.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableRowAction.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/hooks/useRedeemRetryable.ts
- packages/arb-token-bridge-ui/src/state/cctpState.ts
- packages/arb-token-bridge-ui/src/util/AnalyticsUtils.ts
closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/1482
> feat: send events for all networks

- packages/arb-token-bridge-ui/src/util/TokenListUtils.ts
> feat: Add rari mainnet token list

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make eETH withdraw-only

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/TransferPanel/CustomFeeTokenUtils.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- yarn.lock
Bumps Arbitrum SDK to latest stable release which includes custom gas token support, and updates a few methods that got renamed.
Everything should work exactly the same.
> refactor: bump @arbitrum/sdk

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/common/atoms/Switch.tsx
> feat: opacity 70% when toggle is off

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> chore: add rsEth to withdraw only list

- packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
> feat: make chain disclaimer more obvious

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionStatusInfo.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/common/BridgesTable.tsx
- "See transaction history" button
- Hover color in the bridges table
- Network swapper reskin (from https://github.com/OffchainLabs/arbitrum-token-bridge/pull/1546)
> fix: reskin improvements

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenRow.tsx
> feat: add native token text

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
> feat: add no token lists message

- packages/arb-token-bridge-ui/src/pages/_app.tsx
> chore: Reduce sentry sample rate

- packages/arb-token-bridge-ui/src/components/common/NetworkImage.tsx
- packages/arb-token-bridge-ui/src/components/common/NetworkSelectionContainer.tsx
- packages/arb-token-bridge-ui/src/styles/tailwind.css
> feat: add background to network image

- packages/arb-token-bridge-ui/src/util/TokenListUtils.ts
> feat: Add proof of play apex token list

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: add ETHx to the withdraw only list

- packages/arb-token-bridge-ui/src/util/L2ApprovalUtils.ts
> feat: add CU to approval on child chain list

- packages/arb-token-bridge-ui/src/components/common/Layout.tsx
- packages/arb-token-bridge-ui/src/components/common/SiteBanner.tsx
> feat: add arbiscan incident site banner

- packages/arb-token-bridge-ui/src/components/common/Layout.tsx
> feat: take down arbiscan incident site banner

- packages/arb-token-bridge-ui/src/util/CommonAddressUtils.ts
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
- packages/arb-token-bridge-ui/src/util/wagmi/wagmiAdditionalNetworks.ts
> feat: show wCU for CU as symbol on Xai mainnet

- packages/arb-token-bridge-ui/src/pages/_app.tsx
https://github.com/OffchainLabs/arbitrum-token-bridge/pull/1624 didn't filter the error in Sentry. 
Backtick was removed from the regex
> fix: remove backtick from regex for walletconnect error

- packages/arb-token-bridge-ui/src/util/orbitChainsList.ts
> refactor: dodotestnet contract info

- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCDeposit/USDCDepositConfirmationDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/USDCWithdrawal/USDCWithdrawalConfirmationDialog.tsx
- packages/arb-token-bridge-ui/tests/e2e/specs/depositCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
Change the order of cctp and names:
1. Native USDC
2. Native USDC (Third Party Bridge)
3. Wrapped USDC (USDC.e)
> feat: update cctp tabs order and names

- packages/arb-token-bridge-ui/src/util/L2ApprovalUtils.ts
> fix: require approval on L2 for testnet ARB

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/hooks/useNetworks.ts
- packages/arb-token-bridge-ui/src/types/ChainQueryParam.ts
- packages/arb-token-bridge-ui/src/util/bridgeUiConfig.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
- packages/arb-token-bridge-ui/src/util/wagmi/getWagmiChain.ts
- packages/arb-token-bridge-ui/src/util/wagmi/setup.ts
- packages/arb-token-bridge-ui/src/util/wagmi/wagmiAdditionalNetworks.ts
- yarn.lock
> feat: add Stylus Testnet v2

- packages/arb-token-bridge-ui/src/util/orbitChainsList.ts
> feat: add l3x network testnet

- packages/arb-token-bridge-ui/src/util/TokenListUtils.ts
> feat: Add L3X token list

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
> feat: block pop deposit and show banner (hotfix)

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
> fix: usdc withdrawals from L3

- packages/arb-token-bridge-ui/package.json
- yarn.lock
> chore: update cobalt

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/util/TokenUtils.ts
- yarn.lock
Closes FS-598
Custom gateway SDK check: https://github.com/OffchainLabs/arbitrum-sdk/pull/481
Standard gateway SDK check: https://github.com/OffchainLabs/arbitrum-sdk/pull/491
> refactor: check if token is registered using sdk

- packages/arb-token-bridge-ui/src/components/common/Layout.tsx
> feat: add stylus banner

- audit-ci.jsonc
- package.json
- yarn.lock
> fix: Audit GHSA-3h5v-q93c-6h6q

- .github/ISSUE_TEMPLATE/add-layerleap-request.yml
> chore: add Layer Leap request template

- packages/arb-token-bridge-ui/src/util/wagmi/setup.ts
> feat: adds okx wallet to rainbowkit

- .github/ISSUE_TEMPLATE/add-layerleap-request.yml
Can be verified here https://github.com/dewanshparashar/github-form-template-test/issues/new/choose
> chore: update Layer Leap form

- packages/arb-token-bridge-ui/src/util/fastBridges.ts
> feat: hide LI.FI links (hotfix)

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableRowAction.tsx
- packages/arb-token-bridge-ui/src/util/isUserRejectedError.ts
> fix: check if error exists

- packages/arb-token-bridge-ui/package.json
- yarn.lock
> build(deps): bump @arbitrum/sdk from 4.0.0-alpha.9 to 4.0.0

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make ETHFI withdraw-only

- packages/arb-token-bridge-ui/src/util/isUserRejectedError.ts
> fix: handle no error message

- packages/arb-token-bridge-ui/package.json
- yarn.lock
Needs update for E2E's to work locally
> chore: update synpress

- Dockerfile
- yarn.lock
> ci: fix cypress on ci

- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositETH.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
> test: add util for typing in amount

- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/approveToken.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/importToken.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
- packages/arb-token-bridge-ui/tests/support/common.ts
> test: Add findSelectTokenButton command

- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/approveToken.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositETH.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
> test: add util to check for gas label text

- packages/arb-token-bridge-ui/src/components/TransactionHistory/helpers.ts
- packages/arb-token-bridge-ui/src/hooks/useArbTokenBridge.ts
- packages/arb-token-bridge-ui/src/hooks/useClaimWithdrawal.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
> refactor: replace getProvider w getProviderForChainId

- packages/arb-token-bridge-ui/tests/e2e/specfiles.json
> ci: re-enable import token e2e tests

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/TokenBalance.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/utils.ts
> refactor: move token balance to its own file

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/DestinationNetworkBox.tsx
> refactor: move destination network box to its file

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/SourceNetworkBox.tsx
> refactor: move source network box to its file

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableDetailsSteps.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableDetailsTeleporterSteps.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionsTableRowAction.tsx
- packages/arb-token-bridge-ui/src/components/TransactionHistory/helpers.ts
- packages/arb-token-bridge-ui/src/hooks/useRedeemTeleporter.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
- packages/arb-token-bridge-ui/src/hooks/useTransactions.ts
- packages/arb-token-bridge-ui/src/state/app/state.ts
- packages/arb-token-bridge-ui/src/state/app/utils.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/teleport.ts
- packages/arb-token-bridge-ui/src/util/RetryableUtils.ts
- packages/arb-token-bridge-ui/src/util/deposits/helpers.ts
implements the proposed solution from FS-716
> refactor: creates teleporter-specific tx types

- .github/ISSUE_TEMPLATE/add-orbit-chain-request.yml
Added improved headers and descriptions for filling out the forms
> chore: update content in Add Orbit Request issue

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make ATH withdraw-only

- packages/arb-token-bridge-ui/package.json
- yarn.lock
> build(deps): bump cobalt to 0.3.7

- .github/workflows/build-test.yml
- packages/arb-token-bridge-ui/tests/e2e/specfiles.json
> ci: add test name to artifact name

- audit-ci.jsonc
- yarn.lock
See https://github.com/advisories/GHSA-952p-6rrq-rcjv
> build: update to micromatch patch ver

- packages/arb-token-bridge-ui/next.config.js
The current redirection rule has made the og image unavailable
https://bridge.arbitrum.io/og-image.jpg
https://www.opengraph.xyz/url/https%3A%2F%2Fbridge.arbitrum.io
Closes FS-762
> fix: add regex check in nextjs redirection

- packages/arb-token-bridge-ui/package.json
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/SourceNetworkBox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMainInput.tsx
- packages/arb-token-bridge-ui/src/hooks/useArbQueryParams.tsx
- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specfiles.json
- packages/arb-token-bridge-ui/tests/e2e/specs/importToken.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
- packages/arb-token-bridge-ui/tests/support/common.ts
- packages/arb-token-bridge-ui/tests/support/index.ts
- yarn.lock
Memoized max button and amount input
Used local state to hold the amount input
> fix: Improve amount input performance

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make DMT withdraw only

- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useGasEstimates.ts
- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useGasSummary.ts
> fix: make max button work when gas is loading

- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositETH.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/redeemRetryable.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawERC20.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawETH.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
> test: assert that amount is cleared after tx

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/DestinationNetworkBox.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/TokenBalance.tsx
- Small refactoring: Move ETHBalance into NativeCurrencyDestinationBalance
- Remove redundant check in DestinationNetworkBox
Closes FS-820
Closes FS-807
> refactor: remove unnecessary code

- packages/arb-token-bridge-ui/synpress.cctp.config.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
> test: Update withdraw cctp test

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/useMaxAmount.ts
It needs to account for retryable gas but it doesn't currently
> fix: set correct max amount2

- packages/arb-token-bridge-ui/src/hooks/TransferPanel/useGasSummary.ts
- packages/arb-token-bridge-ui/src/hooks/useBalanceOnSourceChain.ts
> fix: native USDC withdrawal gas estimation

- packages/arb-token-bridge-ui/src/components/TransferPanel/AdvancedSettings.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/hooks/useDestinationAddressError.ts
> refactor: create useDestinationAddressError hook

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> chore: make ZRO withdraw only

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/hooks/useIsCctpTransfer.ts
> refactor: extract to useIsCctpTransfer hook

- packages/arb-token-bridge-ui/src/components/TransferPanel/AdvancedSettings.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
> refactor: useDestinationAddressError hook cleanup

- .github/workflows/run-cctp-tests.yml
> test: Allow CCTP tests to be ran with comment

- .github/workflows/run-cctp-tests.yml
> test: Remove CCTP tests on approval

- .github/workflows/e2e-tests.yml
> ci: fix e2e artifact folder name

- yarn.lock
> build(deps): bump express from 4.19.2 to 4.21.0

- packages/arb-token-bridge-ui/src/hooks/useAccountIsBlocked.ts
> fix: remove chain from query key

- packages/arb-token-bridge-ui/src/util/fastBridges.ts
> feat: update router bridge url

- packages/arb-token-bridge-ui/src/components/App/App.tsx
> refactor: use isDepositMode in App.tsx

- audit-ci.jsonc
https://github.com/advisories/GHSA-fc9h-whq2-v747
> ci: exempt new advisory

- packages/arb-token-bridge-ui/src/hooks/__tests__/useNetworks.test.ts
- packages/arb-token-bridge-ui/src/hooks/useNetworks.ts
- packages/arb-token-bridge-ui/src/types/ChainQueryParam.ts
- packages/arb-token-bridge-ui/src/util/networks.ts
> fix: support query params for parents w/o children

- packages/arb-token-bridge-ui/public/images/GeistMainnetLogo.svg
- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/2020
> feat: add Geist Mainnet

- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
> fix: update Social Testnet logo file extension

- packages/arb-token-bridge-ui/src/hooks/useAccountIsBlocked.ts
> feat: send ref with screening request

- .github/ISSUE_TEMPLATE/add-orbit-chain-request.yml
Otherwise yml reads colon as mapping not string
> fix: orbit form image description

- packages/arb-token-bridge-ui/public/images/XaiLogo.svg
> chore: update xai logo

- packages/arb-token-bridge-ui/src/util/networks.ts
closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/1896
> feat: enable LayerLeap for Superposition

- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
- packages/arb-token-bridge-ui/src/util/TokenListUtils.ts
- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
> feat: make L3X chain withdraw-only

- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
closes https://github.com/OffchainLabs/arbitrum-token-bridge/issues/2099
> feat: enable fast withdrawals for Aleph Zero

- packages/arb-token-bridge-ui/src/util/AddressUtils.ts
- packages/arb-token-bridge-ui/src/util/withdrawals/fetchETHWithdrawalsFromEventLogs.ts
- packages/arb-token-bridge-ui/src/util/withdrawals/fetchTokenWithdrawalsFromEventLogs.ts
> perf: don't fetch sender token history if nonce is zero

- yarn.lock
audit ci is flagging https://github.com/advisories/GHSA-mwcw-c2x4-8c55
> build: bump nanoid

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make NST token withdraw only

- packages/arb-token-bridge-ui/src/util/wagmi/setup.ts
> feat: move OKX wallet to Popular

- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
time should be 6 hours for fast withdrawal
> chore: add fast withdrawal time for SX

- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
> chore: increase SX confirm time

- packages/arb-token-bridge-ui/package.json
- yarn.lock
> chore: bump nextjs

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistorySearchBar.tsx
> feat: update tx history search bar placeholder

- packages/arb-token-bridge-ui/src/components/App/AppContext.tsx
> refactor: remove unused app context state

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make USDC USDT withdraw-only on Plume

- packages/arb-token-bridge-ui/src/hooks/useArbQueryParams.tsx
- packages/arb-token-bridge-ui/src/hooks/useTransactionHistory.ts
use `txHistory=0` query param to disable
> feat: add `txHistory` to URL query params

- packages/arb-token-bridge-ui/src/components/TransferPanel/BoLDUpgradeWarning.tsx
> feat: update BoLD warning message

- packages/arb-token-bridge-ui/src/util/networks.ts
https://explorer.superposition.so/address/0xF70ae1Af7D49dA0f7D66Bb55469caC9da336181b
> feat: add Superposition USDC gateway

- packages/arb-token-bridge-ui/src/util/BoLDUtils.ts
> fix: don't include bold confirmation time in tests

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
> fix: show BoLD warning message only when relevant

- packages/arb-token-bridge-ui/src/components/TransferPanel/hooks/useDestinationAddressError.ts
> fix: disable move funds for SCW if dest addr is empty

- packages/arb-token-bridge-ui/src/pages/index.tsx
> fix: only load app after chains are loaded

- packages/arb-token-bridge-ui/src/components/TransferPanel/BoLDUpgradeWarning.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelSummary.tsx
- packages/arb-token-bridge-ui/src/hooks/useTransferDuration.ts
- packages/arb-token-bridge-ui/src/util/BoLDUtils.ts
- packages/arb-token-bridge-ui/src/util/withdrawals/helpers.ts
> fix: update bold banner and confirmation time

- packages/arb-token-bridge-ui/src/util/withdrawals/helpers.ts
> fix: align confirmation time and message status

- packages/arb-token-bridge-ui/src/token-bridge-sdk/BridgeTransferStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20DepositStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20TeleportStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20WithdrawalStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/EthDepositStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/EthTeleportStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/EthWithdrawalStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/OftV2TransferStarter.ts
> fix: Rename TransferEstismateGas

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanelMain/useMaxAmount.ts
> fix: Add check for negative amount in batch transfers

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/ui-driver/UiDriver.test.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriver.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriverCctp.test.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriverCctp.ts
- packages/arb-token-bridge-ui/src/ui-driver/UiDriverTestUtils.ts
> refactor: add ui driver for cctp (part 1)

- packages/arb-token-bridge-ui/src/components/TransactionHistory/TransactionHistorySearchBar.tsx
Show on hover
on mobile it shows on click
Closes FS-1188
> feat: add tooltip to explain address search field

- packages/arb-token-bridge-ui/src/components/TransferPanel/ConnectWalletButton.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
> feat: tx panel connect wallet button

- packages/arb-token-bridge-ui/src/components/TransferPanel/Routes/Route.tsx
- packages/arb-token-bridge-ui/tests/e2e/cypress.d.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/depositCctp.cy.ts
- packages/arb-token-bridge-ui/tests/e2e/specs/withdrawCctp.cy.ts
- packages/arb-token-bridge-ui/tests/support/commands.ts
<table><tr><td><details><summary><b>Depends on #2315.</b> This PR is part of a stack created with <a href="https://github.com/aviator-co/av">Aviator</a>.</summary>
* ➡️ **#2348**
* **#2315**
* **#2279**
* `master`
> test: Fix CCTP tests

- packages/arb-token-bridge-ui/src/components/TransferPanel/Routes/Routes.tsx
> fix: Hide routes if amount is 0

- packages/arb-token-bridge-ui/src/components/TransferPanel/Routes/Route.tsx
> fix: add min-width for route component

- audit-ci.jsonc
- packages/arb-token-bridge-ui/package.json
- yarn.lock
- bumped nextjs minor version
- added a package to `audit-ci.jsonc`
> build: bump dependencies and advisories

- packages/arb-token-bridge-ui/src/token-bridge-sdk/CctpTransferStarter.ts
> fix: use correct owner in cctp allowance check

- packages/arb-token-bridge-ui/src/components/common/SearchPanel/SearchPanelTable.tsx
> feat: make search panel outline look better

- packages/arb-token-bridge-ui/src/components/common/SearchPanel/SearchPanelTable.tsx
focus input after opening the panel
Closes FS-987
> feat: focus on input field when open panel

- packages/arb-token-bridge-ui/src/token-bridge-sdk/BridgeTransferStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/CctpTransferStarter.test.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/CctpTransferStarter.ts
> feat: add cctp token approval tx request method

- packages/arb-token-bridge-ui/src/token-bridge-sdk/OftV2TransferStarter.ts
<table><tr><td><details><summary>This PR is part of a stack created with <a href="https://github.com/aviator-co/av">Aviator</a>.</summary>
* **#2385**
* **#2395**
* **#2396**
* ➡️ **#2402**
* **#2401**
* `master`
> refactor: use address instead of signer for oft

- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/token-bridge-sdk/BridgeTransferStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/CctpTransferStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20DepositStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20TeleportStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/Erc20WithdrawalStarter.ts
- packages/arb-token-bridge-ui/src/token-bridge-sdk/OftV2TransferStarter.ts
<table><tr><td><details><summary>This PR is part of a stack created with <a href="https://github.com/aviator-co/av">Aviator</a>.</summary>
* **#2385**
*  ➡️ **#2395**
* **#2396**
* **#2402**
* **#2401**
* `master`
> feat: use owner address in allowance check

- packages/arb-token-bridge-ui/src/components/common/SafeImage.tsx
> fix: Cache safeImage src

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make Stargate tokens withdraw-only on Plume

- packages/arb-token-bridge-ui/src/components/TransferPanel/hooks/useAmountBigNumber.test.tsx
- packages/arb-token-bridge-ui/src/hooks/__tests__/helpers.ts
> test: Add unit test for useAmountBigNumber

- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadiness.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/useTransferReadinessUtils.ts
- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
Closes FS-1241
+ Also add Plume Legacy to the list
> feat: withdraw-only chains

- yarn.lock
> chore: Update browserlists

- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenSearch.tsx
- packages/arb-token-bridge-ui/src/components/syncers/useBalanceUpdater.tsx
- packages/arb-token-bridge-ui/src/hooks/useBalance.ts
Copy of https://github.com/OffchainLabs/arbitrum-token-bridge/pull/2431. Makes more sense to be merged in the trunk instead of feature branch.
Fixes FS-672
> fix: correct balances after switching accounts

- yarn.lock
as seen on https://github.com/OffchainLabs/arbitrum-token-bridge/actions/runs/15048867155/job/42298335771?pr=2443
> build(deps): fix undici GHSA-cxrh-j4jr-qwg3

- packages/arb-token-bridge-ui/tests/e2e/specs/batchDeposit.cy.ts
> test: Fix batchDeposit assertions

- packages/arb-token-bridge-ui/src/util/__tests__/networks.test.ts
> test: Update unit test

- packages/arb-token-bridge-ui/src/components/TransferPanel/LifiSettings.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenButton.tsx
> fix: Update z-indexes

- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
> fix: Update rari testnet RPC

- packages/arb-token-bridge-ui/src/util/WithdrawOnlyUtils.ts
> feat: make FLUID withdraw-only

- packages/arb-token-bridge-ui/src/token-bridge-sdk/EthDepositStarter.ts
- packages/arb-token-bridge-ui/src/util/EthDepositUtils.ts
> fix: use proper deposit request

- eslint.config.mjs
- packages/arb-token-bridge-ui/src/components/TransactionHistory/helpers.ts
- packages/arb-token-bridge-ui/src/components/TransferPanel/CustomFeeTokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TokenApprovalDialog.tsx
- packages/arb-token-bridge-ui/src/components/TransferPanel/TransferPanel.tsx
- packages/arb-token-bridge-ui/src/token-bridge-sdk/utils.ts
> style: add await-thenable lint rule

- package.json
- packages/arb-token-bridge-ui/package.json
- yarn.lock
> build(deps): bump axios

- packages/arb-token-bridge-ui/public/images/AlterscopeSepolia_Logo.svg
- packages/arb-token-bridge-ui/public/images/AlterscopeSepolia_NativeTokenLogo.svg
- packages/arb-token-bridge-ui/src/util/orbitChainsData.json
> chore: Remove Alterscope sepolia from orbit chain

- packages/arb-token-bridge-ui/src/util/__tests__/networks.test.ts
> fix: Replace xmtp testnet with unite testnet
